# Bikini Bottom residents (expand existing entries)
("Mrs. Puff", "Female", "Nickelodeon", "Pufferfish boating school teacher who constantly fails SpongeBob and inflates with anxiety"),
("Pearl Krabs", "Female", "Nickelodeon", "Teenage whale daughter of Mr. Krabs working at mall and embarrassed by father's cheapness"),
("Larry the Lobster", "Male", "Nickelodeon", "Buff lifeguard lobster at Goo Lagoon beach flexing muscles and epitomizing fitness culture"),
("Karen Plankton", "Female", "Nickelodeon", "Sentient computer screen wife of Plankton who provides sarcastic commentary on his failed schemes"),
("Mermaid Man", "Male", "Nickelodeon", "Elderly semi-retired aquatic superhero parody of Aquaman with starfish sidekick Barnacle Boy"),
("Barnacle Boy", "Male", "Nickelodeon", "Sidekick to Mermaid Man tired of being treated as child despite being elderly himself"),
("Flying Dutchman", "Male", "Nickelodeon", "Ghostly green pirate captain who collects souls and haunts Bikini Bottom with ethereal crew"),
("Old Man Jenkins", "Male", "Nickelodeon", "Elderly fish in overalls who changes appearance every episode and is frequently injured by chaos"),
("Bubble Buddy", "Male", "Nickelodeon", "Sentient bubble created by SpongeBob during loneliness who communicates through squeaks and pops"),
("Dirty Bubble", "Male", "Nickelodeon", "Villainous transparent floating bubble who captures victims alongside Man Ray in retirement home"),
("Man Ray", "Male", "Nickelodeon", "Humanoid manta ray super villain with helmet and ray gun arch-nemesis of Mermaid Man"),
("Patchy the Pirate", "Male", "Nickelodeon", "Live-action pirate president of SpongeBob fan club hosting specials with puppet parrot Potty"),
("Potty the Parrot", "Male", "Nickelodeon", "Crude puppet parrot on Patchy's shoulder making sarcastic comments and causing mechanical chaos"),
("King Neptune", "Male", "Nickelodeon", "Bald green-tailed ruler of the sea with trident and crown frequently visiting Bikini Bottom"),
("Mindy", "Female", "Nickelodeon", "Teenage mermaid daughter of King Neptune helping SpongeBob and Patrick on several occasions"),