export default {
  id: "careers/cat__construction",
  label: "DEPARTMENT :: CONSTRUCTION",
  text: `Construction has 12 open positions on file. Pick one to read the posting.`,
  soulStateDelta: 0,
  choices: [
    { label: "Server Infrastructure Engineer", goto: "careers/job__construction__server_infrastructure_engineer" },
    { label: "Orbital Welder", goto: "careers/job__construction__orbital_welder" },
    { label: "Arcology Architect", goto: "careers/job__construction__arcology_architect" },
    { label: "Subterranean Excavation Specialist", goto: "careers/job__construction__subterranean_excavation_specialist" },
    { label: "Habitat Systems Installer", goto: "careers/job__construction__habitat_systems_installer" },
    { label: "Smart City Integration Engineer", goto: "careers/job__construction__smart_city_integration_engineer" },
    { label: "Zero-G Construction Foreman", goto: "careers/job__construction__zero_g_construction_foreman" },
    { label: "Seismic Retrofitting Specialist", goto: "careers/job__construction__seismic_retrofitting_specialist" },
    { label: "Modular Habitat Assembler", goto: "careers/job__construction__modular_habitat_assembler" },
    { label: "Pressure Vessel Technician", goto: "careers/job__construction__pressure_vessel_technician" },
    { label: "Radiation Shielding Engineer", goto: "careers/job__construction__radiation_shielding_engineer" },
    { label: "Demolition Engineer", goto: "careers/job__construction__demolition_engineer" },
    { label: "[ Back to departments ]", goto: "02b_employment_extended" },
  ],
};
