export default {
  id: "careers/cat__information_technology",
  label: "DEPARTMENT :: INFORMATION TECHNOLOGY",
  text: `Information Technology has 15 open positions on file. Pick one to read the posting.`,
  soulStateDelta: 0,
  choices: [
    { label: "Systems Administrator", goto: "careers/job__information_technology__systems_administrator" },
    { label: "Cloud Infrastructure Architect", goto: "careers/job__information_technology__cloud_infrastructure_architect" },
    { label: "Database Administrator", goto: "careers/job__information_technology__database_administrator" },
    { label: "Network Engineer", goto: "careers/job__information_technology__network_engineer" },
    { label: "DevOps Specialist", goto: "careers/job__information_technology__devops_specialist" },
    { label: "IT Project Manager", goto: "careers/job__information_technology__it_project_manager" },
    { label: "Digital Archivist", goto: "careers/job__information_technology__digital_archivist" },
    { label: "Virtualization Engineer", goto: "careers/job__information_technology__virtualization_engineer" },
    { label: "IT Support Specialist", goto: "careers/job__information_technology__it_support_specialist" },
    { label: "Enterprise Architect", goto: "careers/job__information_technology__enterprise_architect" },
    { label: "Mobile Application Developer", goto: "careers/job__information_technology__mobile_application_developer" },
    { label: "Web Developer", goto: "careers/job__information_technology__web_developer" },
    { label: "Data Center Technician", goto: "careers/job__information_technology__data_center_technician" },
    { label: "Technical Writer", goto: "careers/job__information_technology__technical_writer" },
    { label: "Quality Assurance Engineer", goto: "careers/job__information_technology__quality_assurance_engineer" },
    { label: "[ Back to departments ]", goto: "02b_employment_extended" },
  ],
};
