export default {
  id: "careers/cat__science_research",
  label: "DEPARTMENT :: SCIENCE & RESEARCH",
  text: `Science & Research has 18 open positions on file. Pick one to read the posting.`,
  soulStateDelta: 0,
  choices: [
    { label: "Quantum Chemist", goto: "careers/job__science_research__quantum_chemist" },
    { label: "Dark Matter Researcher", goto: "careers/job__science_research__dark_matter_researcher" },
    { label: "Exoplanetary Atmospheric Scientist", goto: "careers/job__science_research__exoplanetary_atmospheric_scientist" },
    { label: "Synthetic Biologist", goto: "careers/job__science_research__synthetic_biologist" },
    { label: "Neuroscientist", goto: "careers/job__science_research__neuroscientist" },
    { label: "Particle Physicist", goto: "careers/job__science_research__particle_physicist" },
    { label: "Climate Engineer", goto: "careers/job__science_research__climate_engineer" },
    { label: "Materials Scientist", goto: "careers/job__science_research__materials_scientist" },
    { label: "Astrobiologist", goto: "careers/job__science_research__astrobiologist" },
    { label: "Geneticist", goto: "careers/job__science_research__geneticist" },
    { label: "Oceanographer", goto: "careers/job__science_research__oceanographer" },
    { label: "Theoretical Physicist", goto: "careers/job__science_research__theoretical_physicist" },
    { label: "Volcanologist", goto: "careers/job__science_research__volcanologist" },
    { label: "Paleontologist", goto: "careers/job__science_research__paleontologist" },
    { label: "Cognitive Scientist", goto: "careers/job__science_research__cognitive_scientist" },
    { label: "Nanotechnologist", goto: "careers/job__science_research__nanotechnologist" },
    { label: "Seismologist", goto: "careers/job__science_research__seismologist" },
    { label: "Immunologist", goto: "careers/job__science_research__immunologist" },
    { label: "[ Back to departments ]", goto: "02b_employment_extended" },
  ],
};
