export default {
  id: "careers/cat__intelligence_agencies",
  label: "DEPARTMENT :: INTELLIGENCE AGENCIES",
  text: `Intelligence Agencies has 12 open positions on file. Pick one to read the posting.`,
  soulStateDelta: 0,
  choices: [
    { label: "Deep Cover Operative", goto: "careers/job__intelligence_agencies__deep_cover_operative" },
    { label: "Cyber Espionage Agent", goto: "careers/job__intelligence_agencies__cyber_espionage_agent" },
    { label: "Signals Intelligence Analyst", goto: "careers/job__intelligence_agencies__signals_intelligence_analyst" },
    { label: "Counterintelligence Officer", goto: "careers/job__intelligence_agencies__counterintelligence_officer" },
    { label: "Human Intelligence Collector", goto: "careers/job__intelligence_agencies__human_intelligence_collector" },
    { label: "Intelligence AI Trainer", goto: "careers/job__intelligence_agencies__intelligence_ai_trainer" },
    { label: "Covert Action Officer", goto: "careers/job__intelligence_agencies__covert_action_officer" },
    { label: "Technical Surveillance Countermeasures Specialist", goto: "careers/job__intelligence_agencies__technical_surveillance_countermeasures_specialist" },
    { label: "Foreign Intelligence Liaison", goto: "careers/job__intelligence_agencies__foreign_intelligence_liaison" },
    { label: "Intelligence Analyst (All-Source)", goto: "careers/job__intelligence_agencies__intelligence_analyst_all_source" },
    { label: "Clandestine Service Officer", goto: "careers/job__intelligence_agencies__clandestine_service_officer" },
    { label: "Strategic Deception Planner", goto: "careers/job__intelligence_agencies__strategic_deception_planner" },
    { label: "[ Back to departments ]", goto: "02b_employment_extended" },
  ],
};
