export default {
  id: "careers/job__intelligence_agencies__intelligence_analyst_all_source",
  label: "POSTING :: INTELLIGENCE ANALYST (ALL-SOURCE)",
  text: `You synthesize information from every available source—human intelligence, signals intelligence, imagery, open source—into coherent assessments that shape national policy. Your current project is "The Pattern"—an analysis of global events over the past 50 years, searching for connections that others have missed. The Pattern is there. Not a conspiracy, not a plan, but something deeper. A rhythm to history, a pulse to civilization, a cycle that repeats at intervals of approximately 2,500 years. Every cycle ends the same way: a collapse, a dark age, a forgetting, followed by a rebirth. The causes vary—war, plague, climate, technology—but the timing is consistent. And the next cycle is due. Your analysis suggests the trigger will be technological: the development of artificial general intelligence, consciousness uploading, or some other breakthrough that fundamentally alters what it means to be human. The Pattern isn't predictive in detail, but it's clear in outline. Civilization will collapse. Not might. Will. Unless... something changes. Unless someone breaks the cycle. Your report is classified at the highest level, but it's leaking. Not through espionage, but through... resonance. People who read it, even fragments, start seeing the Pattern themselves. They start connecting dots, seeing connections, recognizing the rhythm. It's spreading like a meme, like a virus, like a truth that was waiting to be discovered. Your superiors want you to stop. They say the Pattern is dangerous, that believing in it makes it more likely, that the analysis itself could be the trigger. But you can't unsee it. It's in everything now. The news, the markets, the weather, the dreams. The cycle is turning. The dark age is coming. And somewhere, in the data, in the noise, in the spaces between facts, there's a hint of something else. A variable that doesn't fit the Pattern. An anomaly that could break the cycle. A choice that hasn't been made yet. You're looking for it. The world is looking with you. The Pattern is watching back. And it's whispering: "Find the anomaly. Find the choice. Find the one thing that doesn't repeat. That's where hope lives. That's where the future begins." Your screens are full of data. Your mind is full of patterns. Your heart is full of something that might be hope, or might be desperation. The anomaly is there. You can almost see it. Almost touch it. Almost be it.`,
  soulStateDelta: 0,
  onEnter(state) {
    state.job = "Intelligence Analyst (All-Source)";
    state.jobCategory = "Intelligence Agencies";
  },
  choices: [
    { label: "Take the position.", goto: "03_first_lie_extended" },
    { label: "[ Back to Intelligence Agencies listings ]", goto: "careers/cat__intelligence_agencies" },
  ],
};
