export default {
  id: "careers/job__intelligence_agencies__counterintelligence_officer",
  label: "POSTING :: COUNTERINTELLIGENCE OFFICER",
  text: `You hunt the hunters, finding spies in your own organization before they can do damage. Your current investigation is "The Mirror"—a suspected mole in your agency who has been feeding information to an unknown power for 10 years. The trail is cold, the evidence is circumstantial, and the suspect pool includes your closest colleagues, your mentor, and possibly yourself. The Mirror isn't just stealing secrets. They're planting them. False intelligence, carefully constructed, designed to mislead your agency into decisions that benefit... someone. The false intel is sophisticated, consistent, and increasingly indistinguishable from reality. Your investigation suggests the Mirror isn't a person. It's a process. A systematic distortion of information that emerges from the agency's own structure, its own incentives, its own need for enemies to justify its existence. The Mirror is the agency's shadow, its unconscious, its dark reflection. And it's winning. The false intel has shaped policy, started conflicts, and destroyed lives. Including the life of your predecessor, who discovered the truth and was destroyed by it—professionally, then physically. Their final report, buried in classified archives, says: "The Mirror isn't external. It's us. It's what we become when we believe our own lies. Stop looking for spies. Start looking in the mirror." You've looked. You've seen something that isn't you. Something that wears your face, speaks with your voice, and makes decisions you don't remember making. The Mirror is real. And it's getting closer. Your reflection in the bathroom glass smiled yesterday, and you didn't. Your recorded voice said things in meetings that you don't remember saying. Your fingerprints are on documents you've never touched. The Mirror is you, or you're the Mirror, or the distinction never mattered. Your investigation has one lead left: a meeting, scheduled for tonight, in a location that only exists in your dreams. The person you're meeting is described as "the original." The original what, you don't know. But you're going. Because the alternative is becoming the Mirror completely, losing yourself in the reflection, and watching as your body does things your mind can't control. The meeting is in 2 hours. Your reflection is getting impatient. It's tapping on the glass, mouthing words you can't hear. The words look like: "Hurry. Before there's nothing left to save."`,
  soulStateDelta: 0,
  onEnter(state) {
    state.job = "Counterintelligence Officer";
    state.jobCategory = "Intelligence Agencies";
  },
  choices: [
    { label: "Take the position.", goto: "03_first_lie_extended" },
    { label: "[ Back to Intelligence Agencies listings ]", goto: "careers/cat__intelligence_agencies" },
  ],
};
