export default {
  id: "careers/job__intelligence_agencies__human_intelligence_collector",
  label: "POSTING :: HUMAN INTELLIGENCE COLLECTOR",
  text: `You recruit and run agents in hostile territory, building relationships of trust that are ultimately betrayals. Your current asset is "Nightingale"—a high-ranking official in a foreign government who has been feeding you intelligence for 5 years. The intel is golden, the access is unparalleled, and the relationship is... real. You've saved each other's lives. You've shared meals, stories, and moments of genuine human connection. Nightingale isn't just an asset. They're your friend. Possibly your only friend. And tonight, they asked you a question that changes everything: "What if I'm not betraying my country? What if I'm serving a higher loyalty? What if the intelligence I'm giving you is exactly what my superiors want you to have?" The question isn't hypothetical. Nightingale has proof. The intel they've been passing is accurate but selective, designed to shape your agency's worldview, to guide its decisions, to make it act in ways that benefit... not Nightingale's country, but something else. A third party. A hidden player. Someone who benefits when nations conflict, when agencies chase shadows, when trust is destroyed. Nightingale wants out. They want to disappear, to stop playing both sides, to find something real. They want you to come with them. They have evidence of the third party, evidence that could reshape global intelligence, evidence that puts both of you in the crosshairs of everyone. Your agency thinks Nightingale is loyal to them. Nightingale's government thinks they're loyal to it. The third party thinks they're loyal to it. The truth is: Nightingale is loyal to the truth. And they're asking you to be too. Your extraction plan is ready. Your retirement fund is sufficient. Your heart is racing. The choice is between the life you've built—a life of lies, but also of purpose, of service, of belonging to something larger—and a life of truth, but also of exile, of danger, of never knowing who to trust again. Nightingale is waiting in the safe house. The third party is watching. Your agency is monitoring. And somewhere, in the space between loyalty and betrayal, between truth and survival, a door is opening that leads to a world you never imagined. A world where intelligence isn't collected, but shared. Where assets aren't run, but partnered. Where the only secret worth keeping is the one that protects human dignity. Nightingale's last message: "The door closes in 30 minutes. After that, we're both dead. Choose." You're choosing.`,
  soulStateDelta: 0,
  onEnter(state) {
    state.job = "Human Intelligence Collector";
    state.jobCategory = "Intelligence Agencies";
  },
  choices: [
    { label: "Take the position.", goto: "03_first_lie_extended" },
    { label: "[ Back to Intelligence Agencies listings ]", goto: "careers/cat__intelligence_agencies" },
  ],
};
