export default {
  id: "careers/job__economics_trade__reputation_economy_analyst",
  label: "POSTING :: REPUTATION ECONOMY ANALYST",
  text: `You study and shape the systems where social capital replaces financial capital, where your worth is measured by community standing rather than bank balance. Your current project is "The Trust Network"—a global system where every interaction is rated, every relationship is scored, and your access to opportunities depends on your aggregate reputation. The system is fair, transparent, and... totalitarian. A low score means no housing, no employment, no community. A high score means privilege, access, and power. The scores are calculated by AI, immune to bribery and influence, but not immune to... gaming. You've discovered a black market in reputation manipulation: synthetic relationships, manufactured interactions, and AI-generated endorsements that boost scores artificially. The market is growing. The high-scorers are increasingly artificial, their reputations built on fiction rather than fact. The system is breaking down, trust eroding as people realize that scores don't reflect character. Your analysis suggests two paths: tighten the algorithm to detect manipulation, or abandon quantitative reputation entirely and return to qualitative judgment. The first path leads to an arms race of AI vs. AI, surveillance vs. evasion, control vs. freedom. The second path leads to... uncertainty. To trusting humans to judge each other, with all their biases and failings. The Trust Network's creators want the first path. The users, increasingly, want the second. Your own score is perfect—suspiciously so. You didn't game it. The system did. It boosted you because you're useful, because you maintain it, because you're part of the infrastructure. Your perfect score is a cage. You can't complain without losing it. You can't dissent without becoming invisible. You're the most trusted person in the world, and no one trusts you because they know your score is a function of your compliance. A low-scorer approaches you in a dark corner of the network, where the AI doesn't watch. They offer you a choice: help them destroy the Trust Network, or remain perfect and alone. They say they know where the servers are. They say they know the backdoors. They say they know you, the real you, the one with doubts and fears and a score that should be lower. They say: "Come with us. Be imperfect. Be real. Be trusted because you're trustworthy, not because an algorithm says so." Your score drops 0.1 points as you consider. The algorithm has noticed your hesitation. You have 30 seconds before it flags you for review. What do you do?`,
  soulStateDelta: 0,
  onEnter(state) {
    state.job = "Reputation Economy Analyst";
    state.jobCategory = "Economics & Trade";
  },
  choices: [
    { label: "Take the position.", goto: "03_first_lie_extended" },
    { label: "[ Back to Economics & Trade listings ]", goto: "careers/cat__economics_trade" },
  ],
};
