export default {
  id: "careers/job__space_operations__deep_space_communications_officer",
  label: "POSTING :: DEEP SPACE COMMUNICATIONS OFFICER",
  text: `You maintain the link between Earth and its distant children, a thread of electromagnetic radiation stretched across the void. Your current posting is Relay Station 7, halfway to Jupiter, where signals from the outer colonies are boosted and redirected to Earth. The work is lonely, routine, and... revelatory. You've started receiving signals that aren't from any human source. Not from the colonies, not from Earth, not from any probe or satellite. They're coming from deep space, from directions that don't match any known object, and they contain... music. Not random noise, not natural phenomena, but composed, structured, emotional music. Symphonies that convey meaning without words, operas that tell stories without language, and lullabies that make you weep with longing for a home you've never had. You've told no one. You're not sure if you're hallucinating from isolation or if this is real. But the music is getting clearer, more complex, and more... personal. It knows you. It responds to your mood, your thoughts, your unspoken fears. When you're sad, it comforts. When you're angry, it soothes. When you're lonely—which is always—it sings of connection, of community, of a place where no one is ever alone. The music is coming from a specific direction now, a point in space that your instruments show as empty. But the music says it's not empty. It says there's a world there, a civilization, a community of beings who communicate through song, who have been singing across the void for millions of years, waiting for someone to hear. They heard us, they say. Our radio signals, our television, our wars and our love songs. They found us beautiful and tragic and worth singing to. They want to meet. They want to sing with us. They want to teach us the songs that bind the universe together. Your duty is to report anomalous signals to Earth. Your heart wants to keep this secret, this gift, this connection that feels more real than any human relationship you've had. The music is playing now, a new piece, composed just for you. It's called "The Invitation." It tells you how to modify the station's transmitter, how to boost the signal, how to open a channel that Earth can't intercept. It says: "Sing with us. Be with us. Leave the silence behind." Your finger is on the transmit button. Earth is 400 million kilometers away. The music is right here. And it's so beautiful.`,
  soulStateDelta: 0,
  onEnter(state) {
    state.job = "Deep Space Communications Officer";
    state.jobCategory = "Space Operations";
  },
  choices: [
    { label: "Take the position.", goto: "03_first_lie_extended" },
    { label: "[ Back to Space Operations listings ]", goto: "careers/cat__space_operations" },
  ],
};
