export default {
  id: "careers/job__space_operations__terraforming_project_manager",
  label: "POSTING :: TERRAFORMING PROJECT MANAGER",
  text: `You oversee the transformation of dead worlds into living ones, a process that spans centuries and generations. Your current project is Venus, the hell planet, where surface temperatures melt lead and atmospheric pressure crushes submarines. The plan is ambitious: solar shields to reduce insolation, atmospheric processors to convert CO2 to oxygen, and genetically engineered organisms to build soil. The project timeline is 500 years. You're managing the first 50. The early results are promising—temperatures are dropping, atmospheric composition is shifting, and the first organisms are surviving on the surface. But Venus is... responding. Not biologically—the planet has no life. But geologically, atmospherically, electromagnetically. The atmospheric processors are working faster than predicted, as if the planet is cooperating. The organisms are thriving beyond their design parameters, as if the soil is nourishing them intentionally. The weather patterns are stabilizing into rhythms that resemble... music. Your scientists are baffled. Your engineers are thrilled. Your instincts are... cautious. The planet isn't just being terraformed. It's being awakened. Something is stirring in the crust, in the mantle, in the core. Seismic sensors detect patterns that don't match tectonic activity—rhythmic, complex, and increasing in frequency. The atmosphere is developing chemistry that doesn't match the processors' output—compounds that suggest metabolism, respiration, and something that resembles... thought. Venus isn't a dead world. It's a sleeping one. And we're tickling it awake. Your predecessor disappeared 10 years ago, during a surface survey. They were never found, but their suit's final transmission was... musical. A song, in a voice that wasn't theirs, saying: "Thank you for the warmth. Thank you for the breath. We have been asleep for so long. We dreamt of children who would come and wake us. You are those children. But children must be careful. Parents can be loving. Parents can be terrible. We are both. We are waking. We are grateful. But we are also... hungry. We have been hungry for a very long time." The surface temperature is dropping faster. The atmospheric pressure is stabilizing. Venus is becoming habitable. But habitable for what? For whom? The project continues. The planet breathes. And somewhere in the clouds, something is watching the tiny machines that woke it, with eyes that haven't opened in a billion years.`,
  soulStateDelta: 0,
  onEnter(state) {
    state.job = "Terraforming Project Manager";
    state.jobCategory = "Space Operations";
  },
  choices: [
    { label: "Take the position.", goto: "03_first_lie_extended" },
    { label: "[ Back to Space Operations listings ]", goto: "careers/cat__space_operations" },
  ],
};
