export default {
  id: "careers/job__intelligence_agencies__technical_surveillance_countermeasures_specialist",
  label: "POSTING :: TECHNICAL SURVEILLANCE COUNTERMEASURES SPECIALIST",
  text: `You find the bugs, taps, and surveillance devices that others hide, protecting privacy in an age of universal monitoring. Your current client is "The Hermit"—a billionaire who has retreated to a private island, claiming that every electronic device is compromised and only absolute physical isolation can ensure security. You've swept the island three times. No bugs, no taps, no surveillance. But the Hermit insists they're being watched. They describe specific conversations, private moments, thoughts they never spoke aloud, that have been revealed to them through... dreams. Vivid, consistent, detailed dreams of being observed by figures that don't exist, in places they've never been, doing things they don't remember. Your professional assessment: paranoia, possibly induced by isolation, possibly by neurological condition. Your personal assessment: something else. The dreams match across multiple nights, forming a narrative. The observers in the dreams aren't hostile. They're... curious. Scientific. Documenting. The Hermit isn't just being watched in the dreams. They're being studied. Your investigation leads to a discovery that breaks your professional composure: the dreams are real. Not hallucinations, not psychological, but actual observations, transmitted through a medium you don't understand, from observers who exist in a state that doesn't match physical reality. They're watching from... nearby. From a dimension adjacent to ours, accessible through sleep, through dreams, through the state between waking and sleeping. The Hermit has attracted their attention by trying so hard to avoid attention. They're fascinated by the attempt. They want to see how far the Hermit will go. They want to see how far you'll go. Your countermeasures are useless against dream surveillance. Your professional pride is wounded. But your curiosity is engaged. The observers have noticed you noticing them. They've started appearing in your dreams too. They're offering a trade: access to their observations of human history, complete and unfiltered, in exchange for... cooperation. They want to understand why humans hide. Why we seek privacy. What we do when we think no one is watching. They promise not to judge. They promise to share what they learn. They promise that the truth, once known, can't be unknown. Your dreams tonight will be the negotiation. Your waking tomorrow will be the decision. The Hermit is waiting for your report. The observers are waiting for your answer. And somewhere, in the space between sleep and waking, a new kind of surveillance is being born. One that watches from inside. One that sees everything. One that never sleeps.`,
  soulStateDelta: 0,
  onEnter(state) {
    state.job = "Technical Surveillance Countermeasures Specialist";
    state.jobCategory = "Intelligence Agencies";
  },
  choices: [
    { label: "Take the position.", goto: "03_first_lie_extended" },
    { label: "[ Back to Intelligence Agencies listings ]", goto: "careers/cat__intelligence_agencies" },
  ],
};
