export default {
  id: "careers/cat__manufacturing",
  label: "DEPARTMENT :: MANUFACTURING",
  text: `Manufacturing has 12 open positions on file. Pick one to read the posting.`,
  soulStateDelta: 0,
  choices: [
    { label: "3D Fabrication Specialist", goto: "careers/job__manufacturing__3d_fabrication_specialist" },
    { label: "Weapon Fabricator", goto: "careers/job__manufacturing__weapon_fabricator" },
    { label: "Nanofabrication Engineer", goto: "careers/job__manufacturing__nanofabrication_engineer" },
    { label: "Assembly Line Optimization Specialist", goto: "careers/job__manufacturing__assembly_line_optimization_specialist" },
    { label: "Quality Control Inspector", goto: "careers/job__manufacturing__quality_control_inspector" },
    { label: "Synthetic Materials Chemist", goto: "careers/job__manufacturing__synthetic_materials_chemist" },
    { label: "Industrial Robotics Technician", goto: "careers/job__manufacturing__industrial_robotics_technician" },
    { label: "Precision Machinist", goto: "careers/job__manufacturing__precision_machinist" },
    { label: "Biomanufacturing Specialist", goto: "careers/job__manufacturing__biomanufacturing_specialist" },
    { label: "Supply Chain Quality Auditor", goto: "careers/job__manufacturing__supply_chain_quality_auditor" },
    { label: "Additive Manufacturing Architect", goto: "careers/job__manufacturing__additive_manufacturing_architect" },
    { label: "Cleanroom Operations Manager", goto: "careers/job__manufacturing__cleanroom_operations_manager" },
    { label: "[ Back to departments ]", goto: "02b_employment_extended" },
  ],
};
