export default {
  id: "careers/cat__space_operations",
  label: "DEPARTMENT :: SPACE OPERATIONS",
  text: `Space Operations has 15 open positions on file. Pick one to read the posting.`,
  soulStateDelta: 0,
  choices: [
    { label: "Colony Governor", goto: "careers/job__space_operations__colony_governor" },
    { label: "Stellar Observatory Director", goto: "careers/job__space_operations__stellar_observatory_director" },
    { label: "Orbital Habitat Designer", goto: "careers/job__space_operations__orbital_habitat_designer" },
    { label: "Asteroid Mining Operations Chief", goto: "careers/job__space_operations__asteroid_mining_operations_chief" },
    { label: "Interplanetary Diplomat", goto: "careers/job__space_operations__interplanetary_diplomat" },
    { label: "Zero-G Manufacturing Supervisor", goto: "careers/job__space_operations__zero_g_manufacturing_supervisor" },
    { label: "Space Traffic Controller", goto: "careers/job__space_operations__space_traffic_controller" },
    { label: "Extravehicular Activity Specialist", goto: "careers/job__space_operations__extravehicular_activity_specialist" },
    { label: "Planetary Defense Coordinator", goto: "careers/job__space_operations__planetary_defense_coordinator" },
    { label: "Lunar Base Administrator", goto: "careers/job__space_operations__lunar_base_administrator" },
    { label: "Deep Space Communications Officer", goto: "careers/job__space_operations__deep_space_communications_officer" },
    { label: "Orbital Debris Removal Specialist", goto: "careers/job__space_operations__orbital_debris_removal_specialist" },
    { label: "Terraforming Project Manager", goto: "careers/job__space_operations__terraforming_project_manager" },
    { label: "Space Medicine Researcher", goto: "careers/job__space_operations__space_medicine_researcher" },
    { label: "Extraterrestrial Resource Assessor", goto: "careers/job__space_operations__extraterrestrial_resource_assessor" },
    { label: "[ Back to departments ]", goto: "02b_employment_extended" },
  ],
};
