export default {
  id: "careers/cat__engineering",
  label: "DEPARTMENT :: ENGINEERING",
  text: `Engineering has 22 open positions on file. Pick one to read the posting.`,
  soulStateDelta: 0,
  choices: [
    { label: "Terraforming Engineer", goto: "careers/job__engineering__terraforming_engineer" },
    { label: "Mega-Structure Designer", goto: "careers/job__engineering__mega_structure_designer" },
    { label: "Aerospace Engineer", goto: "careers/job__engineering__aerospace_engineer" },
    { label: "Nuclear Engineer", goto: "careers/job__engineering__nuclear_engineer" },
    { label: "Civil Engineer", goto: "careers/job__engineering__civil_engineer" },
    { label: "Robotics Engineer", goto: "careers/job__engineering__robotics_engineer" },
    { label: "Biomechanical Engineer", goto: "careers/job__engineering__biomechanical_engineer" },
    { label: "Structural Engineer", goto: "careers/job__engineering__structural_engineer" },
    { label: "Environmental Engineer", goto: "careers/job__engineering__environmental_engineer" },
    { label: "Marine Engineer", goto: "careers/job__engineering__marine_engineer" },
    { label: "Geotechnical Engineer", goto: "careers/job__engineering__geotechnical_engineer" },
    { label: "Electrical Engineer", goto: "careers/job__engineering__electrical_engineer" },
    { label: "Chemical Engineer", goto: "careers/job__engineering__chemical_engineer" },
    { label: "Industrial Engineer", goto: "careers/job__engineering__industrial_engineer" },
    { label: "Telecommunications Engineer", goto: "careers/job__engineering__telecommunications_engineer" },
    { label: "Control Systems Engineer", goto: "careers/job__engineering__control_systems_engineer" },
    { label: "Acoustic Engineer", goto: "careers/job__engineering__acoustic_engineer" },
    { label: "Transportation Engineer", goto: "careers/job__engineering__transportation_engineer" },
    { label: "Energy Systems Engineer", goto: "careers/job__engineering__energy_systems_engineer" },
    { label: "Nanotechnology Engineer", goto: "careers/job__engineering__nanotechnology_engineer" },
    { label: "Agricultural Engineer", goto: "careers/job__engineering__agricultural_engineer" },
    { label: "Optical Engineer", goto: "careers/job__engineering__optical_engineer" },
    { label: "[ Back to departments ]", goto: "02b_employment_extended" },
  ],
};
