export default {
  id: "careers/cat__medical_biosystem",
  label: "DEPARTMENT :: MEDICAL & BIOSYSTEM",
  text: `Medical & Biosystem has 16 open positions on file. Pick one to read the posting.`,
  soulStateDelta: 0,
  choices: [
    { label: "Nano-Medicine Specialist", goto: "careers/job__medical_biosystem__nano_medicine_specialist" },
    { label: "Neural Surgeon", goto: "careers/job__medical_biosystem__neural_surgeon" },
    { label: "Genetic Counselor", goto: "careers/job__medical_biosystem__genetic_counselor" },
    { label: "Trauma Surgeon", goto: "careers/job__medical_biosystem__trauma_surgeon" },
    { label: "Epidemiologist", goto: "careers/job__medical_biosystem__epidemiologist" },
    { label: "Psychiatrist", goto: "careers/job__medical_biosystem__psychiatrist" },
    { label: "Prosthetist", goto: "careers/job__medical_biosystem__prosthetist" },
    { label: "Immunologist", goto: "careers/job__medical_biosystem__immunologist" },
    { label: "Emergency Medical Technician", goto: "careers/job__medical_biosystem__emergency_medical_technician" },
    { label: "Pathologist", goto: "careers/job__medical_biosystem__pathologist" },
    { label: "Reproductive Endocrinologist", goto: "careers/job__medical_biosystem__reproductive_endocrinologist" },
    { label: "Anesthesiologist", goto: "careers/job__medical_biosystem__anesthesiologist" },
    { label: "Medical AI Ethicist", goto: "careers/job__medical_biosystem__medical_ai_ethicist" },
    { label: "Regenerative Medicine Specialist", goto: "careers/job__medical_biosystem__regenerative_medicine_specialist" },
    { label: "Exobiomedical Researcher", goto: "careers/job__medical_biosystem__exobiomedical_researcher" },
    { label: "Cryonics Specialist", goto: "careers/job__medical_biosystem__cryonics_specialist" },
    { label: "[ Back to departments ]", goto: "02b_employment_extended" },
  ],
};
