export default {
  id: "careers/cat__military_defense",
  label: "DEPARTMENT :: MILITARY & DEFENSE",
  text: `Military & Defense has 18 open positions on file. Pick one to read the posting.`,
  soulStateDelta: 0,
  choices: [
    { label: "Orbital Marine", goto: "careers/job__military_defense__orbital_marine" },
    { label: "Tactical Enforcement Officer", goto: "careers/job__military_defense__tactical_enforcement_officer" },
    { label: "Drone Wing Commander", goto: "careers/job__military_defense__drone_wing_commander" },
    { label: "Special Reconnaissance Operative", goto: "careers/job__military_defense__special_reconnaissance_operative" },
    { label: "Cyber Warfare Specialist", goto: "careers/job__military_defense__cyber_warfare_specialist" },
    { label: "Orbital Defense Artillerist", goto: "careers/job__military_defense__orbital_defense_artillerist" },
    { label: "Biological Defense Officer", goto: "careers/job__military_defense__biological_defense_officer" },
    { label: "Strategic Deterrence Analyst", goto: "careers/job__military_defense__strategic_deterrence_analyst" },
    { label: "Combat Medic", goto: "careers/job__military_defense__combat_medic" },
    { label: "Military Intelligence Analyst", goto: "careers/job__military_defense__military_intelligence_analyst" },
    { label: "Psyops Specialist", goto: "careers/job__military_defense__psyops_specialist" },
    { label: "Orbital Drop Shock Trooper", goto: "careers/job__military_defense__orbital_drop_shock_trooper" },
    { label: "Counter-Insurgency Specialist", goto: "careers/job__military_defense__counter_insurgency_specialist" },
    { label: "Autonomous Weapons Systems Operator", goto: "careers/job__military_defense__autonomous_weapons_systems_operator" },
    { label: "Military Quantum Strategist", goto: "careers/job__military_defense__military_quantum_strategist" },
    { label: "Exo-Armor Pilot", goto: "careers/job__military_defense__exo_armor_pilot" },
    { label: "Defense Acquisition Officer", goto: "careers/job__military_defense__defense_acquisition_officer" },
    { label: "Joint Force Space Component Commander", goto: "careers/job__military_defense__joint_force_space_component_commander" },
    { label: "[ Back to departments ]", goto: "02b_employment_extended" },
  ],
};
