export default {
  id: "careers/cat__cybersecurity",
  label: "DEPARTMENT :: CYBERSECURITY",
  text: `Cybersecurity has 12 open positions on file. Pick one to read the posting.`,
  soulStateDelta: 0,
  choices: [
    { label: "Red Team Operator", goto: "careers/job__cybersecurity__red_team_operator" },
    { label: "Blue Team Architect", goto: "careers/job__cybersecurity__blue_team_architect" },
    { label: "Quantum Cryptographer", goto: "careers/job__cybersecurity__quantum_cryptographer" },
    { label: "Incident Response Commander", goto: "careers/job__cybersecurity__incident_response_commander" },
    { label: "Malware Analyst", goto: "careers/job__cybersecurity__malware_analyst" },
    { label: "Identity & Access Management Specialist", goto: "careers/job__cybersecurity__identity_access_management_specialist" },
    { label: "Threat Intelligence Analyst", goto: "careers/job__cybersecurity__threat_intelligence_analyst" },
    { label: "Penetration Testing Lead", goto: "careers/job__cybersecurity__penetration_testing_lead" },
    { label: "Secure Software Developer", goto: "careers/job__cybersecurity__secure_software_developer" },
    { label: "Cyber Forensics Investigator", goto: "careers/job__cybersecurity__cyber_forensics_investigator" },
    { label: "Zero-Day Broker", goto: "careers/job__cybersecurity__zero_day_broker" },
    { label: "Security Awareness Trainer", goto: "careers/job__cybersecurity__security_awareness_trainer" },
    { label: "[ Back to departments ]", goto: "02b_employment_extended" },
  ],
};
