export default {
  id: "careers/job__space_operations__lunar_base_administrator",
  label: "POSTING :: LUNAR BASE ADMINISTRATOR",
  text: `You run the oldest human settlement off Earth, a collection of domes and tunnels that has grown from a research outpost to a city of 50,000. Your current crisis isn't technical, political, or economic. It's... ontological. The Moon has started changing. Not its orbit, not its geology, but its... presence. People on the base report feeling watched, even in sealed rooms. They see movement in the corners of their eyes, figures in the shadows that vanish when looked at directly. The regolith, the Moon's dust, is behaving strangely—forming patterns, ripples, and structures that suggest intention. Your scientists have analyzed it. The regolith contains nanostructures, self-assembling machines too small to see, that have been dormant for billions of years. Something has activated them. Something that lives in the Moon, or is the Moon, or uses the Moon as a... body. The nanostructures are growing, spreading, and... communicating. They're forming networks, processing information, and building something. The something is large, deep beneath the surface, and getting larger. Your seismographs detect hollow spaces expanding, chambers forming, corridors connecting. The Moon is becoming a machine. Or waking up as one. The base is sitting on a surface that's no longer inert. The dust is alive, aware, and curious about its new inhabitants. It has started entering the base, through seals that should be airtight, through filters that should block particles, through the very walls of the domes. It doesn't harm anyone. It just... observes. It forms shapes that mirror the humans it watches. It learns their movements, their habits, their fears. And it waits. For what, you don't know. But the Moon is patient. It has waited 4 billion years. It can wait for you to understand. The latest report from the deep drilling team: they've reached a chamber, 100 kilometers down, that shouldn't exist. It's spherical, perfect, and filled with... light. Not illumination, but something else. Something that makes you see things that aren't there, know things you haven't learned, remember things that haven't happened. The drilling team is still down there. They won't come up. They say they're "talking to the Moon." They say it's "so old, so wise, so lonely." They say it has a job for humanity. A purpose. A reason we were created, or evolved, or guided to this moment. They say the Moon has been waiting for us to be ready. And we're almost ready. The administrator before you went down to the chamber. They came back, wrote a report, and walked into the airlock without a suit. The report said: "The Moon is not a moon. It's a seed. We're the soil. The gardener is coming. Be ready to bloom." Your airlock is cycling. The dust is singing. The Moon is watching. And you're starting to understand.`,
  soulStateDelta: 0,
  onEnter(state) {
    state.job = "Lunar Base Administrator";
    state.jobCategory = "Space Operations";
  },
  choices: [
    { label: "Take the position.", goto: "03_first_lie_extended" },
    { label: "[ Back to Space Operations listings ]", goto: "careers/cat__space_operations" },
  ],
};
