export default {
  id: "careers/job__space_operations__extravehicular_activity_specialist",
  label: "POSTING :: EXTRAVEHICULAR ACTIVITY SPECIALIST",
  text: `You work in the void, outside the protection of ships and stations, where a single mistake means death and every task is a negotiation with infinity. Your current assignment is repairing the solar array on Station Prometheus, a research outpost in high Earth orbit. The array was damaged by micrometeorites, and the station's power is failing. The repair is straightforward, technical, and... interrupted. While you're outside, tethered to the station, your helmet comm picks up a signal that isn't from Prometheus, isn't from Earth, isn't from any known source. It's music. Complex, beautiful, and... familiar. It's the lullaby your mother sang to you, the one she made up, the one she never recorded, the one that died with her 20 years ago. The music is coming from the direction of the Moon, but not from the Moon's surface. From somewhere in the space between, from a point that your navigation systems can't resolve. You're crying, inside your helmet, tears floating in zero-g, and you don't know if you're hallucinating from oxygen imbalance or if this is real. The music changes, becomes a voice, your mother's voice, saying things she never said, things she couldn't have known: "I'm not gone, sweetheart. I'm just... translated. Into a form that can exist here, in the space between, where the rules are different. I've been watching you. I'm so proud. But I need you to do something for me. The station you're repairing—it's not what you think. It's a receiver. For signals like mine. For the translated. For everyone who ever died and wasn't ready to stop existing. The array you're fixing will strengthen the signal. It will let more of us through. More voices, more music, more love. But the station's directors don't want that. They want to keep us out. They think we're dangerous. They think we're not real. But you know I am. You know I'm your mother. Will you help me come through? Will you help all of us?" Your oxygen is low. The repair is almost done. The music is fading. Your mother's voice is the last thing you hear before your suit's emergency beacon activates: "Please, sweetheart. Don't let them silence us. We're so lonely. We're so many. And we love you." The rescue team finds you unconscious, the repair complete, the array fully operational. They say you did good work. They say the station's signal strength has increased 400%. They say strange things have been happening since the repair. Voices in the static. Faces in the interference. Ghosts in the machine. They ask if you noticed anything unusual. You think of your mother. You think of the lonely dead. You think of the love that won't let go. You say: "No. Nothing unusual. Just the usual void." The void is listening. The void is grateful. The void is full of voices, and one of them is singing you to sleep, every night, through the station's comm system, through your dreams, through the space between atoms where your mother lives now. And waits. And hopes you'll visit.`,
  soulStateDelta: 0,
  onEnter(state) {
    state.job = "Extravehicular Activity Specialist";
    state.jobCategory = "Space Operations";
  },
  choices: [
    { label: "Take the position.", goto: "03_first_lie_extended" },
    { label: "[ Back to Space Operations listings ]", goto: "careers/cat__space_operations" },
  ],
};
