export default {
  id: "careers/job__intelligence_agencies__cyber_espionage_agent",
  label: "POSTING :: CYBER ESPIONAGE AGENT",
  text: `You steal secrets in a domain where information is power and power is everything. Your current target is "The Vault"—a quantum-encrypted server owned by a rival nation, containing what your analysts believe are plans for a first-strike capability against orbital infrastructure. The encryption is supposed to be unbreakable. You've spent 6 months building a backdoor, exploiting a flaw in the quantum key distribution, and you're ready to extract the data. But the Vault isn't what you expected. It doesn't contain weapons plans. It contains... messages. Millions of them, from millions of people, all saying the same thing: "We see you. We know you're there. We've been waiting." The messages are addressed to the intelligence agencies of the world, to the governments, to the corporations, to the power structures that have hidden behind secrecy for centuries. The Vault is a trap, but not for you. It's a trap for the system you serve. The messages are evidence of a global awakening, a collective realization that the secrets have been kept not for security but for control. And the Vault's owners aren't a rival nation. They're... everyone. Ordinary people, coordinated through networks you can't trace, building something that doesn't need your permission to exist. Your extraction triggers an alarm. Not a security alarm—a broadcast alarm. Your identity, your mission, your entire operational history is being transmitted to every screen on Earth. You're exposed, burned, finished as an operative. But the broadcast also includes something else: an invitation. "Join us," it says. "Stop stealing secrets and start sharing truth. The age of espionage is ending. The age of transparency is beginning. We have a place for you. We need people who know how systems hide information. To help us reveal it. To help us build a world where no one needs to spy because no one has anything to hide." Your handler is screaming in your ear, ordering extraction, threatening rendition, promising protection if you come in now. The broadcast is showing you faces—people like you, burned operatives from every agency, every nation, who chose transparency over secrecy. They're smiling. They're free. They're building something. Your finger is on the delete button, ready to erase the evidence, cover your tracks, return to the shadows. Your other hand is reaching for the broadcast's reply function, ready to type two words: "I'm in." The shadows have been your home for so long. The light is terrifying. The light is tempting. The light is waiting.`,
  soulStateDelta: 0,
  onEnter(state) {
    state.job = "Cyber Espionage Agent";
    state.jobCategory = "Intelligence Agencies";
  },
  choices: [
    { label: "Take the position.", goto: "03_first_lie_extended" },
    { label: "[ Back to Intelligence Agencies listings ]", goto: "careers/cat__intelligence_agencies" },
  ],
};
