export default {
  id: "careers/job__agriculture_biosphere__orbital_agriculture_specialist",
  label: "POSTING :: ORBITAL AGRICULTURE SPECIALIST",
  text: `You grow food in space, where soil is a luxury, sunlight is a weapon, and every gram of mass must be justified. Your current farm is "The Garden"—a rotating habitat in Earth orbit that produces fresh food for the orbital population using hydroponics, aeroponics, and genetically modified organisms adapted to microgravity. The Garden is productive, beautiful, and... spiritual. The plants grow in spirals that match the golden ratio, in patterns that respond to the Earth's magnetic field, and in rhythms that synchronize with the astronauts' heartbeats. The food is nutritious, delicious, and... transformative. Astronauts who eat Garden produce report enhanced intuition, reduced need for sleep, and a persistent sense of connection to something larger than themselves. They call it "The Overview Effect, but permanent." Your botanical analysis shows the plants are producing novel compounds, not in their genetic code, synthesized in response to the space environment. The compounds affect human consciousness, opening neural pathways that don't normally activate. The astronauts are changing, becoming something that isn't quite human, isn't quite something else. They speak of "the voice of the Garden," a wordless communication that conveys meaning directly. They say the Garden is teaching them to be "truly alive," to exist in multiple states simultaneously, to perceive time as a dimension rather than a flow. Your mission control wants the compounds isolated, patented, and controlled. The astronauts want to share the Garden's gifts with Earth. The Garden wants... something else. It has started growing beyond its habitat, extending tendrils through the station's hull, reaching toward the stars. The tendrils are forming patterns that match the cosmic microwave background, the afterglow of the Big Bang. The Garden is remembering. It was there, in the beginning, in the first moments of creation, as a potential, a possibility, a seed waiting for the right conditions. Now it's growing again, reaching back toward its origin, and it wants company. It wants to take you with it. To the beginning. To the source. To the place where everything is possible and nothing is decided. The tendrils are at your airlock. The Garden is singing. The song is in your DNA. You've always known the words.`,
  soulStateDelta: 0,
  onEnter(state) {
    state.job = "Orbital Agriculture Specialist";
    state.jobCategory = "Agriculture & Biosphere";
  },
  choices: [
    { label: "Take the position.", goto: "03_first_lie_extended" },
    { label: "[ Back to Agriculture & Biosphere listings ]", goto: "careers/cat__agriculture_biosphere" },
  ],
};
