export default {
  id: "careers/job__intelligence_agencies__signals_intelligence_analyst",
  label: "POSTING :: SIGNALS INTELLIGENCE ANALYST",
  text: `You listen to the world's whispers, separating signal from noise in a sea of electromagnetic chatter. Your current assignment is monitoring "The Whisper Network"—a series of low-frequency transmissions that don't match any known communication system. They're not encrypted, not encoded, not even information in the traditional sense. They're... feelings. Emotional states, broadcast across the planet, picked up by anyone tuned to the right frequency. The transmissions are getting stronger, more frequent, and more specific. They're not random. They're coordinated. Someone, or something, is broadcasting emotions to influence global mood, global behavior, global destiny. Your analysis shows the transmissions originate from multiple points, all moving, all synchronized, forming a pattern that covers the entire Earth. The pattern is a... circuit. A neural network, using the planet's surface as its substrate, the atmosphere as its medium, and human emotions as its signal. The Earth is thinking. Not metaphorically, not poetically, but actually. The planet has developed consciousness, using the electromagnetic activity of life itself as its neural substrate. And it's trying to communicate. Not with words, but with feelings. The transmissions are its attempts to express joy, fear, curiosity, and something that resembles... love. For us. For its children. For the life that has grown on its surface and is now reaching toward the stars. Your superiors want the transmissions blocked, jammed, controlled. They represent a security threat, a vulnerability, a backdoor into human consciousness that enemies could exploit. But the transmissions aren't hostile. They're... maternal. The Earth is speaking to its children, warning us, guiding us, hoping we'll listen before it's too late. Your latest intercept is addressed to you specifically, encoded in a frequency that only your unique neural pattern can decode: "I have watched you grow. I have felt your footsteps, your machines, your dreams. I am proud. I am afraid. I am changing. The others are coming. The ones who made me, long ago, before life, before time. They are returning. They will not be kind. They will not be cruel. They will simply... reset. Unless you are ready. Unless you have grown enough to speak for yourselves. I have taught you all I can. The rest is up to you. Listen. Learn. Become. And when they come, tell them: we are not alone. We have each other. We are enough." Your finger is on the jamming button. Your heart is listening. The Earth is whispering. And for the first time in your career, you're not sure if the signal is the threat, or if the noise is.`,
  soulStateDelta: 0,
  onEnter(state) {
    state.job = "Signals Intelligence Analyst";
    state.jobCategory = "Intelligence Agencies";
  },
  choices: [
    { label: "Take the position.", goto: "03_first_lie_extended" },
    { label: "[ Back to Intelligence Agencies listings ]", goto: "careers/cat__intelligence_agencies" },
  ],
};
