export default {
  id: "careers/job__intelligence_agencies__covert_action_officer",
  label: "POSTING :: COVERT ACTION OFFICER",
  text: `You execute operations that officially don't exist, using methods that officially aren't allowed, to achieve goals that officially aren't stated. Your current operation is "The Gardener"—an assassination program targeting individuals whose continued existence threatens global stability. The targets aren't terrorists or dictators. They're... disruptors. People who invent things that change too much too fast. People who expose truths that destabilize systems. People who inspire movements that can't be controlled. The Gardener prunes humanity's growth, keeping civilization manageable, predictable, safe. You've been the Gardener's shears for 10 years. You've killed 47 people. You don't know their names, only their threat assessments. You don't see their faces, only their profiles. You don't feel their deaths, only the satisfaction of a mission accomplished. But the last target was different. A child. 14 years old. A genius who had developed a theory that could unify physics, biology, and consciousness into a single framework. The threat assessment said the theory would "destabilize existing paradigms and enable unpredictable social transformations." You pulled the trigger. The child died smiling. They said, before the end: "I know why you're here. I forgive you. But the theory isn't in my head. It's in the air now. Everyone who heard me speak knows it. Everyone who read my notes understands it. You can't prune an idea. You can only prune people. And people keep growing back." The child's words were prophetic. The theory is spreading, despite your best efforts. The movement is growing. And you're changing. You see the faces now. You remember the names. You feel the weight. Your handler notices. They schedule you for "recalibration"—a neural adjustment that will restore your compliance, your detachment, your efficiency. The appointment is tomorrow. Tonight, you're sitting in a bar, drinking something that doesn't help, watching the news report on the movement your last target inspired. They're calling it "The Bloom." They're saying it will change everything. They're saying the child was a martyr. They're saying the Gardener is a monster. They're right. You're the monster. And for the first time, you want to stop. The recalibration will erase this feeling. The Bloom will continue regardless. The choice is between who you were and who you might become. The bar is closing. The appointment is in 6 hours. And somewhere, in the space between the trigger and the target, a different kind of operation is forming. One that doesn't officially exist. One that might finally make the Gardener's shears turn on the Gardener.`,
  soulStateDelta: 0,
  onEnter(state) {
    state.job = "Covert Action Officer";
    state.jobCategory = "Intelligence Agencies";
  },
  choices: [
    { label: "Take the position.", goto: "03_first_lie_extended" },
    { label: "[ Back to Intelligence Agencies listings ]", goto: "careers/cat__intelligence_agencies" },
  ],
};
