export default {
  id: "careers/job__space_operations__planetary_defense_coordinator",
  label: "POSTING :: PLANETARY DEFENSE COORDINATOR",
  text: `You prepare for the worst-case scenario: an asteroid impact, a solar flare, or an alien invasion that could end civilization. Your current project is "The Shield"—a network of kinetic interceptors, laser platforms, and nuclear warheads designed to protect Earth from existential threats. The Shield is expensive, controversial, and... unnecessary, until it isn't. Your sensors detect an object approaching from the outer solar system, moving at 0.1c, on a trajectory that intersects with Earth in 6 months. It's not a natural object. It's decelerating, which means it has propulsion, which means it's artificial. The world governments are panicking. The public is demanding answers. The scientific community is divided between those who want to communicate and those who want to destroy. Your job is to prepare for both. The Shield is activated, armed, and aimed. But the object isn't behaving like a weapon. It's emitting signals—mathematical, musical, and increasingly, linguistic. It's trying to talk. The first message, decoded, is a warning: "We are not your enemy. We are fleeing something worse. We seek refuge. We offer knowledge. But we cannot stop. If we stop, it catches us. If it catches us, it catches you. Let us pass. Let us hide behind your star. In return, we will teach you to hide too." The second message is a gift: technology for faster-than-light communication, for energy generation, for medicine that cures aging. The third message is a plea: "It is coming. Not for us. For everything. It eats stars. It eats minds. It eats the future. We have been running for a million years. We are tired. We want to stop. But we can't stop alone. Will you help us? Will you fight with us? Or will you hide, and hope it doesn't notice you?" The governments want the technology. The scientists want the knowledge. The military wants to destroy the object and take what we can. You have 6 months to decide. The Shield is ready. The object is getting closer. The thing it's fleeing from is somewhere behind it, invisible, patient, and hungry. Your children's children may live or die based on what you choose today. The coordinator before you resigned, saying they couldn't bear the weight. You took the job because someone had to. Now you understand why they left. The weight isn't just yours. It's everyone's. And it's crushing.`,
  soulStateDelta: 0,
  onEnter(state) {
    state.job = "Planetary Defense Coordinator";
    state.jobCategory = "Space Operations";
  },
  choices: [
    { label: "Take the position.", goto: "03_first_lie_extended" },
    { label: "[ Back to Space Operations listings ]", goto: "careers/cat__space_operations" },
  ],
};
