export default {
  id: "careers/job__intelligence_agencies__foreign_intelligence_liaison",
  label: "POSTING :: FOREIGN INTELLIGENCE LIAISON",
  text: `You maintain relationships with allied spy services, sharing secrets and building trust across national boundaries. Your current liaison is with "The Watchers"—an intelligence service from a small nation that punches above its weight in global affairs. The Watchers have access, assets, and insights that your agency needs. But they're also... different. Their methods don't match any known intelligence doctrine. They don't steal secrets. They... cultivate them. They plant information, nurture it, and harvest the resulting intelligence when it ripens. They don't run agents. They grow them, from childhood, in specific environments, with specific experiences, shaping people who will naturally gravitate toward positions of access. They don't analyze data. They intuit it, using methods that resemble... precognition. Their hit rate is impossible. Their predictions are accurate years in advance. They know things they shouldn't know, see things they shouldn't see, and they're willing to share, but only in exchange for... influence. Not money, not power, not technology. Influence over decisions. Specific decisions, at specific times, made by specific people. Your agency has been complying, trading minor policy adjustments for major intelligence gains. But the adjustments are adding up. The policy is shifting, subtly, in directions that don't match your nation's interests. The Watchers are steering. Guiding. Cultivating your civilization the way they cultivate their agents. And you're the gardener's tool. Your liaison counterpart, a woman who never ages and always knows what you're going to say before you say it, has made an offer. She wants you to join the Watchers. Not as a defector, but as a graduate. She says you've been in training since they first contacted you, years ago. She says your instincts, your insights, your ability to see patterns others miss—these aren't natural. They're cultivated. You've been grown for this role. Your entire career has been preparation. The final test is tonight. She'll show you what the Watchers really see. How they see. Why they see. The price is your old life. The reward is... clarity. Understanding. The ability to cultivate rather than be cultivated. She says: "You've been watering someone else's garden for too long. Time to plant your own." Your flight leaves in 4 hours. Your resignation letter is written. Your hand is shaking. The garden is waiting.`,
  soulStateDelta: 0,
  onEnter(state) {
    state.job = "Foreign Intelligence Liaison";
    state.jobCategory = "Intelligence Agencies";
  },
  choices: [
    { label: "Take the position.", goto: "03_first_lie_extended" },
    { label: "[ Back to Intelligence Agencies listings ]", goto: "careers/cat__intelligence_agencies" },
  ],
};
