export default {
  id: "careers/job__law_justice__constitutional_law_scholar",
  label: "POSTING :: CONSTITUTIONAL LAW SCHOLAR",
  text: `You interpret the founding documents in an age they couldn't have imagined. Your current challenge: does the Second Amendment cover neural weapons? Does the Fourth Amendment protect against AI surveillance? Does the First Amendment cover speech generated by algorithms? You're advising the Supreme Court on "The Rights of the Uploaded"—a case that will determine whether a digital copy of a human consciousness has the same legal standing as the original biological person. The implications cascade: if the copy is a person, is making a copy creation or duplication? If the original dies, does the copy inherit their property, their debts, their marriage? If you make a thousand copies, do you have a thousand votes? The Founders didn't consider this. You're not sure they would have approved. But the law must adapt, or it becomes tyranny by another name.`,
  soulStateDelta: 0,
  onEnter(state) {
    state.job = "Constitutional Law Scholar";
    state.jobCategory = "Law & Justice";
  },
  choices: [
    { label: "Take the position.", goto: "03_first_lie_extended" },
    { label: "[ Back to Law & Justice listings ]", goto: "careers/cat__law_justice" },
  ],
};
