#!/usr/bin/env python3
"""gen_element_table.py — regenerate ElementMatchupTable.h from the canonical 21x21 CSV.
Usage: python gen_element_table.py <matrix.csv> <out.h>
Single source of truth = gamedata/canon/ELEMENT_MATCHUP_MATRIX_21.csv
WIN=1.25, LOSS=0.75, SELF=0.5 (CEO 07.13)."""
import sys, csv

WIN, LOSS, SELF = 1.25, 0.75, 0.5

def main():
    src, out = sys.argv[1], sys.argv[2]
    with open(src, encoding="utf-8") as f:
        rows = list(csv.reader(f))
    header = rows[0]                       # first cell is empty (row-label col); keep it
    elem = header[1:]  # 21 names
    assert len(elem) == 21, f"expected 21 elements, got {len(elem)}"
    data = {}
    for r in rows[1:]:
        r = [c for c in r if c != ""]
        if not r: continue
        name = r[0]
        vals = [int(x) for x in r[1:]]
        data[name] = vals
    assert len(data) == 21, f"expected 21 rows, got {len(data)}"

    lines = []
    lines.append("// GENERATED by gen_element_table.py — DO NOT EDIT BY HAND")
    lines.append("#pragma once")
    lines.append('#include "CoreMinimal.h"')
    lines.append('#include "../../Core/Types/TrinityMatrixTypes.h"')
    lines.append("")
    lines.append("static constexpr int32 MATCHUP_N = 21;")
    lines.append("// Index order: " + ",".join(elem))
    lines.append("static constexpr float ElementMatchup[MATCHUP_N][MATCHUP_N] = {")
    for name in elem:
        vals = data[name]
        assert len(vals) == 21, f"{name} has {len(vals)} cols"
        floats = []
        for v in vals:
            floats.append(f"{SELF if v==0 else (WIN if v==1 else LOSS)}f")
        lines.append(f"/*{name:<6}*/ {{{', '.join(floats)}}},")
    lines.append("};")
    with open(out, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {out}: 21x21 table, WIN={WIN} LOSS={LOSS} SELF={SELF}")

if __name__ == "__main__":
    main()
