
[/Script/EngineSettings.GameMapsSettings]
GameDefaultMap=/Engine/Maps/Templates/OpenWorld
GlobalDefaultGameMode=/Script/R3ALN3T_UE5.MenuGameMode

[/Script/CommonUI.CommonUISettings]
CommonButtonAcceptKeyHandling=TriggerClick

[ConsoleVariables]
CommonUI.CheckKeyboardFocusAndParentage=1
CommonUI.DisallowUserFocusedWidgetForPendingFocusRecipient=1
CommonUI.FallbackToDesiredOnAutoRestoreFailure=1

[/Script/EngineSettings.GeneralProjectSettings]
ProjectID=E99C4016464EE28761768983C8819E41

[/Script/AssetReferenceRestrictions.AssetReferencingPolicySettings]
bUseAssetReferenceRestrictions=False

; Chapter 9: Standalone Alpha packaging configuration.
[/Script/UnrealEd.ProjectPackagingSettings]
BuildConfiguration=Shipping
bUsePak=True
bCookAllMaps=True
bCompressed=True
bIncludeDebugFiles=False
bStripDebugInfoFromExe=False
bDeployWithBulkDataInPak=True
bIncludeNativeSubsystems=True
bIncludeBaseRedist=True
bIncludeAppLocalPrerequisites=True
bShouldMountPakFile=True
bGenerateChunks=False
bShareMaterialShaderCode=True
bSharedMaterialNativeLibraries=True
bSkipEditorContent=True
PackingDirType=RelativeToProjectRoot
bIncludePartiallyUsedPackagesOnly=False
StagedBuildDirectoryOverride=Builds/Release


