import csv

# ============================================================
# CONFIGURATION
# ============================================================
OUTPUT_FILE = "animated_characters.csv"

# ============================================================
# CHARACTER DATABASE (expand as needed)
# Each entry: (Character Name, Gender, Network/Brand, Descriptor)
# ============================================================
characters = [
    # ====================
    # Cartoon Network
    # ====================
    ("Finn the Human", "Male", "Cartoon Network", "Brave teenage boy in blue shorts and white bear-ear hat wielding swords across post-apocalyptic fantasy realm with magical dog brother"),
    ("Jake the Dog", "Male", "Cartoon Network", "Yellow stretchy shape-shifting magical bulldog with laid-back wisdom using elastic powers to assist brother on heroic quests"),
    ("Princess Bubblegum", "Female", "Cartoon Network", "Hyper-intelligent pink bubblegum humanoid ruler of Candy Kingdom balancing scientific genius with monarchal duties"),
    ("Marceline the Vampire Queen", "Female", "Cartoon Network", "Thousand-year-old vampire with pale grey skin long black hair and red bass guitar navigating immortality and emotional vulnerability"),
    ("Ice King", "Male", "Cartoon Network", "Blue-skinned ice-powered elderly wizard with long white beard and golden crown driven to kidnap princesses due to magical crown-induced madness"),
    ("BMO", "Male", "Cartoon Network", "Small sentient green gaming console robot with cheerful childlike personality living in Finn and Jake's treehouse"),
    ("Lumpy Space Princess", "Female", "Cartoon Network", "Floating purple cloud-shaped teenager with valley-girl accent and dramatic self-absorbed attitude from Lumpy Space dimension"),
    ("Gumball Watterson", "Male", "Cartoon Network", "Mischievous twelve-year-old blue cat navigating surreal suburban life with adopted goldfish brother and rabbit sister in eccentric family"),
    ("Darwin Watterson", "Male", "Cartoon Network", "Orange goldfish who grew legs and became adopted Watterson family member known for innocent optimism and pure heart"),
    ("Anais Watterson", "Female", "Cartoon Network", "Precocious four-year-old pink rabbit with oversized head and genius-level intellect often the most rational member of Watterson family"),
    ("Richard Watterson", "Male", "Cartoon Network", "Obese pink rabbit and stay-at-home father defined by extreme laziness childlike naivety and unexpected moments of profound stupidity"),
    ("Nicole Watterson", "Female", "Cartoon Network", "Blue cat mother and overworked office employee with intense competitive streak and near-superhuman protective maternal rage"),
    ("Steven Universe", "Male", "Cartoon Network", "Compassionate half-human half-Gem boy with curly dark hair pink star t-shirt and shield-summoning powers protecting Earth with magical guardians"),
    ("Garnet", "Female", "Cartoon Network", "Tall stoic fusion Gem with square afro and visor sunglasses embodying literal relationship between Ruby and Sapphire with future vision powers"),
    ("Amethyst", "Female", "Cartoon Network", "Short purple Gem with white hair whip-wielding abilities shapeshifting powers and playful rebellious personality masking deep insecurity"),
    ("Pearl", "Female", "Cartoon Network", "Slim white Gem with pointed nose ballet-like combat style obsessive organization and devoted protective nature toward Steven"),
    ("Peridot", "Female", "Cartoon Network", "Small green Gem technician with triangular hair and limb-enhancers initially Homeworld antagonist later redeemed eccentric ally obsessed with Earth culture"),
    ("Lapis Lazuli", "Female", "Cartoon Network", "Blue water-controlling Gem with backstory of imprisonment and trauma possessing immense hydrokinetic power and melancholic demeanor"),
    ("Ben Tennyson", "Male", "Cartoon Network", "Brown-haired teenage boy wearing Omnitrix alien transformation device on wrist enabling access to dozens of extraterrestrial hero forms"),
    ("Gwen Tennyson", "Female", "Cartoon Network", "Red-haired cousin of Ben with innate magical Anodite heritage wielding mana-based energy manipulation and genius-level intellect"),
    ("Kevin Levin", "Male", "Cartoon Network", "Dark-haired antihero with ability to absorb matter and energy into his body transforming into living composite material with conflicted reformed past"),
    ("Max Tennyson", "Male", "Cartoon Network", "Elderly grandfather and retired Plumber agent with Hawaiian shirt extensive alien-hunting experience and surprising combat proficiency"),
    ("Rex Salazar", "Male", "Cartoon Network", "Teenage amnesiac infected with nanites granting ability to grow massive biomechanical weapons from body seeking identity while fighting EVO threats"),
    ("Mordecai", "Male", "Cartoon Network", "Tall blue anthropomorphic jay with white markings working as groundskeeper at park navigating young adult apathy and friendship dynamics"),
    ("Rigby", "Male", "Cartoon Network", "Short brown anthropomorphic raccoon with hyperactive immature personality often instigating supernatural chaos due to competitive jealousy and laziness"),
    ("Benson", "Male", "Cartoon Network", "Orange gumball machine with authority position as park manager prone to explosive temper outbursts but genuinely caring about employee well-being"),
    ("Skips", "Male", "Cartoon Network", "White-haired muscular yeti with centuries of experience and arcane knowledge serving as park's handyman and source of supernatural guidance"),
    ("Muscle Man", "Male", "Cartoon Network", "Overweight green-skinned prankster with signature white tank top frequently telling off-color jokes and surprisingly competent in various odd skills"),
    ("High-Five Ghost", "Male", "Cartoon Network", "Small translucent ghost with hand-shaped appendage on head serving as Muscle Man's silent best friend and occasional voice of reason"),
    ("Pops Maellard", "Male", "Cartoon Network", "Eccentric elderly lollipop-headed gentleman with childlike innocence old-timey speech patterns and secret interdimensional origins"),
    ("Numbuh 1", "Male", "Cartoon Network", "Bald British-accented child operative of secret global kids' organization wearing dark sunglasses and red sweater leading Sector V against adult tyranny"),
    ("Numbuh 2", "Male", "Cartoon Network", "Overweight aviation-obsessed kid with blue pilot cap and goggles serving as team's mechanical genius and comic relief with thick accent"),
    ("Numbuh 3", "Female", "Cartoon Network", "Hyper-cheerful Japanese girl in oversized green sweater with extreme love for Rainbow Monkeys and surprisingly fierce combat abilities"),
    ("Numbuh 4", "Male", "Cartoon Network", "Short-tempered Australian boy in orange hoodie serving as team's primary brawler with fists-first approach and constant bickering with Numbuh 3"),
    ("Numbuh 5", "Female", "Cartoon Network", "Cool collected African-American girl in red cap and blue vest serving as second-in-command with deadpan humor and secret candy-hoarding habit"),
    ("Ed", "Male", "Cartoon Network", "Tall yellow-skinned simpleton with short red hair and green jacket defined by extreme physical strength low intelligence and obsessive love of gravy"),
    ("Edd (Double D)", "Male", "Cartoon Network", "Intelligent neurotic boy with black ski cap covering unknown secret extremely organized and literate serving as moral center of Ed trio"),
    ("Eddy", "Male", "Cartoon Network", "Short loud arrogant con-artist in yellow shirt with red stripe constantly scheming for jawbreakers and money using elaborate scams in cul-de-sac"),
    ("Courage the Cowardly Dog", "Male", "Cartoon Network", "Pink anxious dog with large eyes and chattering teeth living in middle of Nowhere forced to confront supernatural horrors to protect elderly owner Muriel"),
    ("Muriel Bagge", "Female", "Cartoon Network", "Kind elderly Scottish woman in purple dress who took in Courage and sees good in everything often oblivious to monstrous threats around her"),
    ("Eustace Bagge", "Male", "Cartoon Network", "Cranky bald elderly farmer with thick glasses and green cap constantly threatening Courage with rolling pin and obsessed with mysterious trucker hat"),
    ("Mac", "Male", "Cartoon Network", "Eight-year-old boy with dark hair and glasses serving as straight-man and creator of imaginary friend Bloo dealing with adoption and growing up"),
    ("Bloo", "Male", "Cartoon Network", "Small blue domed imaginary friend with selfish manipulative personality resembling thumb-tack shape created by Mac now living at Foster's Home"),
    ("Wilt", "Male", "Cartoon Network", "Tall red one-armed imaginary friend with basketball motif defined by extreme politeness compulsive apologies and inability to say no"),
    ("Eduardo", "Male", "Cartoon Network", "Large purple bull-like imaginary friend with Spanish accent and horns paradoxically gentle and cowardly despite frightening appearance"),
    ("Coco", "Female", "Cartoon Network", "Eccentric chicken-bird-palm tree imaginary friend who communicates only by saying Coco and lays plastic eggs containing various objects"),
    ("Frankie Foster", "Female", "Cartoon Network", "Red-haired teenage caretaker and granddaughter of Madame Foster managing daily chaos of imaginary friend household with exhausted competence"),
    ("Mojo Jojo", "Male", "Cartoon Network", "Evil genius chimpanzee with large green brain-exposed helmet and cape who monologues extensively while plotting destruction of Powerpuff Girls"),
    ("Him", "Male", "Cartoon Network", "Demonic flamboyant lobster-clawed entity with high-pitched voice serving as most terrifying villain of Powerpuff Girls with reality-bending powers"),
    ("Billy", "Male", "Cartoon Network", "Extremely unintelligent boy with oversized nose and red cap whose stupidity causes apocalyptic chaos often alongside sarcastic scythe-wielding Grim"),
    ("Mandy", "Female", "Cartoon Network", "Monotone perpetually unimpressed blonde girl who controls Grim through intellect and sheer force of will never smiling and effortlessly villainous"),
    ("Grim", "Male", "Cartoon Network", "Jamaican-accented personification of Death in black robe who lost scythe to two children and is now forced into bizarre servitude and friendship"),
    ("Robot Jones", "Male", "Cartoon Network", "Retro-styled humanoid robot attending middle school to observe human behavior communicating through monotone voice and flashing light bulbs"),
    ("Junkyard Dog / Juniper Lee", "Female", "Cartoon Network", "Asian-American teenage girl serving as Protector of magical balance between human and monster worlds using inherited powers and martial arts"),
    ("Chowder", "Male", "Cartoon Network", "Purple cat-bear-rabbit hybrid apprentice chef in Marzipan City with voracious appetite and tendency to eat anything including customers and ingredients"),
    ("Mung Daal", "Male", "Cartoon Network", "Elderly blue-skinned master chef with walrus mustache running catering company while dealing with chaotic apprentice and surreal culinary adventures"),
    ("Shnitzel", "Male", "Cartoon Network", "Grey stone golem-like sous chef who communicates exclusively by saying Radda and performs heavy kitchen labor with stoic resignation"),
    ("Flapjack", "Male", "Cartoon Network", "Small blonde enthusiastic boy raised in whale mouth with talking dolphin seeking mythical Candied Island while getting into maritime misadventures"),
    ("Captain K'nuckles", "Male", "Cartoon Network", "Lazy blue-skinned old sea captain with wooden flippers and peg-hands who lies about past exploits while exploiting Flapjack's naivety"),
    ("Uncle Grandpa", "Male", "Cartoon Network", "Surreal magical relative figure with rainbow suspenders and fanny pack who visits children to help with bizarre reality-warping solutions and catchphrases"),
    ("Clarence Wendle", "Male", "Cartoon Network", "Optimistic chubby elementary school boy with bowl haircut finding wonder and joy in mundane suburban life through pure enthusiasm"),
    ("K.O.", "Male", "Cartoon Network", "Small energetic boy with red bandana working at hero supply bodega aspiring to become greatest hero while discovering own powerful origins"),

    # ====================
    # Adult Swim
    # ====================
    ("Rick Sanchez", "Male", "Adult Swim", "Cynical genius alcoholic mad scientist with wild grey-blue hair and white lab coat utilizing interdimensional technology while exhibiting extreme emotional detachment"),
    ("Morty Smith", "Male", "Adult Swim", "Nervous easily traumatized 14-year-old high school student wearing yellow t-shirt constantly dragged into dangerous cosmic anomalies by grandfather"),
    ("Summer Smith", "Female", "Adult Swim", "Typical teenage girl and Morty's older sister seeking validation through popularity gradually becoming more involved in interdimensional adventures"),
    ("Beth Smith", "Female", "Adult Swim", "Horse surgeon with abandonment issues stemming from Rick's disappearance struggling between cynicism inherited from father and desire to be good parent"),
    ("Jerry Smith", "Male", "Adult Swim", "Pathetically insecure unemployed advertising agent frequently mocked by Rick representing everything average and mediocre about conventional human existence"),
    ("Mr. Poopybutthole", "Male", "Adult Swim", "Small yellow top-hat-wearing long-time family friend who is actually a real character despite absurd name providing emotional support through fourth-wall awareness"),
    ("Birdperson", "Male", "Adult Swim", "Spartan-like bird-human hybrid warrior and Rick's best friend from revolutionary days speaking in stoic literal statements representing honor and sacrifice"),
    ("Master Shake", "Male", "Adult Swim", "Obnoxious narcissistic milkshake cup with straw who constantly abuses and exploits his roommates while demonstrating complete incompetence"),
    ("Frylock", "Male", "Adult Swim", "Floating box of french fries serving as responsible intelligent leader of Aqua Teens using laser-shooting abilities and fry-based attacks"),
    ("Meatwad", "Male", "Adult Swim", "Naive shapeless ball of compressed meat with childlike personality capable of shapeshifting and regenerating often exploited by Master Shake"),
    ("Carl Brutananadilewski", "Male", "Adult Swim", "Overweight balding mustached neighbor in tank top and sweatpants obsessed with sports cars classic rock and casual misogyny"),
    ("Space Ghost", "Male", "Adult Swim", "Former superhero turned late-night talk show host in white suit interviewing celebrities with deadpan awkwardness and hidden existential despair"),
    ("Zorak", "Male", "Adult Swim", "Green mantis-like alien bandleader with deep hatred for Space Ghost forced into musical accompaniment role while openly expressing homicidal contempt"),
    ("Moltar", "Male", "Adult Swim", "Lava-based robot wearing containment suit serving as director and producer for Space Ghost's show while maintaining technical professionalism"),
    ("Brock Samson", "Male", "Adult Swim", "Mulleted hyper-violent government agent and bodyguard with knife obsession possessing near-superhuman combat abilities and deadpan delivery"),
    ("Dr. Venture", "Male", "Adult Swim", "Balding middle-aged failed super-scientist son of legendary inventor struggling with inadequacy and raising two naive sons in world of costumed adventure"),
    ("Dean Venture", "Male", "Adult Swim", "Sensitive nerdy teenage boy in red turtleneck discovering identity outside of being twin brother while dealing with inherited legacy of super-science"),
    ("Hank Venture", "Male", "Adult Swim", "Confident adventurous teenage boy in blue bandana eager for action and danger despite complete lack of self-awareness and frequent physical harm"),
    ("The Monarch", "Male", "Adult Swim", "Butterfly-themed supervillain in orange and black costume with obsessive vendetta against Dr. Venture and surprisingly competent arch-nemesis dedication"),
    ("Dr. Girlfriend", "Female", "Adult Swim", "Deep-voiced Number Two to Monarch in Jackie O-style fashion with white suit and pillbox hat exuding intelligence and loyalty beyond villainous role"),
    ("Tim and Eric", "Male", "Adult Swim", "Surrealist comedy duo producing intentionally awkward low-budget sketches featuring celebrity guests and disturbing corporate parody aesthetic"),
    ("Eric Andre", "Male", "Adult Swim", "Chaotic talk show host destroying set and psychologically tormenting celebrity guests through absurdist anti-comedy and manic energy"),
    ("Black Dynamite", "Male", "Adult Swim", "Blaxploitation-style kung-fu master and former CIA agent speaking in hyper-masculine cadence while fighting corruption in 1970s setting"),
    ("Harvey Birdman", "Male", "Adult Swim", "Former winged superhero turned defense attorney in suit representing cartoon characters in surreal legal cases with deadpan absurdity"),
    ("Peter Potamus", "Male", "Adult Swim", "Purple hippopotamus lawyer in colonial attire working alongside Harvey Birdman with bombastic inappropriate personality and predatory behavior"),

    # ====================
    # Nickelodeon / Nicktoons / Nick Jr.
    # ====================
    ("SpongeBob SquarePants", "Male", "Nickelodeon", "Hyper-optimistic porous yellow kitchen sponge living in pineapple wearing crisp white collared shirt red tie and brown square pants dedicated to fry-cooking"),
    ("Patrick Star", "Male", "Nicktoons (brand)", "Dim-witted heavily out-of-shape pink starfish wearing green shorts with purple flowers defined by naive slow-spoken innocence and extreme loyalty"),
    ("Squidward Tentacles", "Male", "Nickelodeon", "Arrogant deeply cynical turquoise octopus with large bulbous nose wearing brown shirt who despises neighbors and fancies himself elite clarinetist and artist"),
    ("Mr. Krabs", "Male", "Nickelodeon", "Red clawed crab with tall eyestalks and money-obsessed personality owning Krusty Krab restaurant valuing profit above all including daughter's happiness"),
    ("Sandy Cheeks", "Female", "Nickelodeon", "Texas-accented athletic squirrel in underwater dome suit practicing karate and science while being only land creature in Bikini Bottom"),
    ("Plankton", "Male", "Nickelodeon", "Tiny green single-eyed copepod constantly scheming to steal secret Krabby Patty formula from Mr. Krabs using elaborate inventions and disguises"),
    ("Gary the Snail", "Male", "Nickelodeon", "Blue shelled housecat-like pet snail of SpongeBob who meows despite being invertebrate and possesses hidden intelligence and royal ancestry"),
    ("Tommy Pickles", "Male", "Nickelodeon", "Brave inquisitive one-year-old toddler with bald head wearing blue shirt and diaper acting as natural leader of friend group with toy plastic screwdriver"),
    ("Chuckie Finster", "Male", "Nickelodeon", "Orange-haired bespectacled neurotic toddler with oversized purple glasses perpetually scared yet loyal enough to follow Tommy into any adventure"),
    ("Angelica Pickles", "Female", "Nicktoons", "Spoiled manipulative three-year-old girl with blonde pigtails in purple bows wearing orange dress acting as bossy authority figure over toddlers"),
    ("Phil DeVille", "Male", "Nickelodeon", "Twin toddler in green shirt alongside sister Lil known for fascination with dirt worms and eating gross things with complete enthusiasm"),
    ("Lil DeVille", "Female", "Nickelodeon", "Twin toddler in pink shirt alongside brother Phil sharing his gross interests while being slightly more socially aware in Rugrats group"),
    ("Susie Carmichael", "Female", "Nickelodeon", "Talented kind-hearted African-American toddler in yellow dress with purple pants serving as angelic foil and occasional rival to Angelica"),
    ("Dil Pickles", "Male", "Nickelodeon", "Infant younger brother of Tommy introduced later in series defined by crying drooling and object-flinging abilities as baby character"),
    ("Arnold Shortman", "Male", "Nickelodeon", "Football-headed nine-year-old boy in blue sweater living with grandparents in urban boarding house offering wisdom and moral guidance to neighborhood kids"),
    ("Gerald Johanssen", "Male", "Nickelodeon", "Tall black-haired boy with stack hairstyle serving as Arnold's best friend keeping detailed urban legends collection and acting as loyal hype-man"),
    ("Helga Pataki", "Female", "Nickelodeon", "Blonde unibrowed bully girl in pink dress with secret obsessive love shrine dedicated to Arnold hidden behind aggressive hostile exterior"),
    ("Aang", "Male", "Nickelodeon", "Bald tattooed twelve-year-old last Airbender and Avatar frozen in iceberg for century now must master all four elements to restore world balance"),
    ("Katara", "Female", "Nickelodeon", "Water Tribe teenage waterbender with hair loop braids and blue clothing serving as team healer and moral compass while mastering bending arts"),
    ("Sokka", "Male", "Nickelodeon", "Non-bending Water Tribe warrior with ponytail and boomerang compensating for lack of powers through sarcasm strategy and eventual sword mastery"),
    ("Toph Beifong", "Female", "Nickelodeon", "Blind twelve-year-old earthbending prodigy from wealthy family who escaped overprotective parents becoming greatest earthbender through seismic-sense technique"),
    ("Zuko", "Male", "Nickelodeon", "Scarred exiled Fire Nation prince with shaved head and ponytail on redemption arc from antagonist to ally seeking honor through Avatar's guidance"),
    ("Iroh", "Male", "Nickelodeon", "Elderly wise tea-loving Fire Nation general and Zuko's uncle known for firebending mastery calm philosophy and profound quotes about life"),
    ("Appa", "Male", "Nickelodeon", "Massive fluffy white six-legged flying sky bison serving as loyal animal companion and transportation method for Team Avatar with gentle personality"),
    ("Momo", "Male", "Nickelodeon", "Green-eyed winged lemur discovered by Aang acting as comic relief animal companion and occasional scout for Team Avatar"),
    ("Korra", "Female", "Nickelodeon", "Muscular Water Tribe teenage Avatar with brown hair and blue clothing following Aang's legacy in industrializing world facing political revolution and spirit threats"),
    ("Mako", "Male", "Nickelodeon", "Black-haired firebender with red scarf and brooding personality serving as Republic City cop and early love interest before complex relationship evolution"),
    ("Bolin", "Male", "Nickelodeon", "Earthbending brother of Mako with green eyes and lovable goofball personality skilled in pro-bending arena and lava-bending discovery"),
    ("Asami Sato", "Female", "Nickelodeon", "Elegant black-haired non-bender heiress to Future Industries with engineering genius piloting skills and eventual romantic partnership with Korra"),
    ("Lincoln Loud", "Male", "Nickelodeon", "White-haired eleven-year-old only boy among ten sisters in chaotic household navigating survival through cunning plans and orange polo shirt"),
    ("Lori Loud", "Female", "Nickelodeon", "Eldest bossy sister in blue with blonde hair constantly on phone discussing literally everything while managing long-distance boyfriend Bobby"),
    ("Leni Loud", "Female", "Nickelodeon", "Fashion-obsessed blonde sister in turquoise with ditzy personality and kind heart who shows surprising intelligence in clothing design and empathy"),
    ("Luna Loud", "Female", "Nickelodeon", "Rock music-loving sister in purple with short brown hair and faux-British accent playing electric guitar and aspiring to musical stardom"),
    ("Luan Loud", "Female", "Nickelodeon", "Pun-obsessed sister in yellow with braces and pigtails delivering constant jokes and pranks while occasionally revealing ventriloquist skills"),
    ("Lynn Loud Jr.", "Female", "Nickelodeon", "Athletic sister in red jersey with brown hair excelling at every sport while struggling with competitiveness and superstition rituals"),
    ("Lucy Loud", "Female", "Nickelodeon", "Goth sister in black with pale skin and long black hair covering face delivering monotone poems about death while secretly soft-hearted"),
    ("Lola Loud", "Female", "Nickelodeon", "Pageant-obsessed twin sister in pink dress and blonde curls with deceptively sweet appearance masking ruthless competitive princess personality"),
    ("Lana Loud", "Female", "Nickelodeon", "Tomgirl twin sister in red cap and overalls obsessed with mud frogs plumbing and all things filthy opposite of pageant twin Lola"),
    ("Lisa Loud", "Female", "Nickelodeon", "Child genius sister in glasses and green turtleneck with PhD-level intellect conducting dangerous experiments while still wearing diapers"),
    ("Lily Loud", "Female", "Nickelodeon", "Infant youngest sister in purple onesie who occasionally displays surprising abilities like teleportation and lost treasure location"),
    ("Jimmy Neutron", "Male", "Nickelodeon", "Boy genius with oversized head and gravity-defying brown swirl hair inventing gadgets that frequently cause Retroville chaos while candy-addicted"),
    ("Carl Wheezer", "Male", "Nickelodeon", "Allergic asthmatic best friend in glasses with obsessive love of llamas and nervous disposition providing anxious commentary on Jimmy's adventures"),
    ("Sheen Estevez", "Male", "Nickelodeon", "Hyperactive friend with green jacket and uncontrollable enthusiasm for Ultra Lord superhero franchise acting as comedic hype-man"),
    ("Cindy Vortex", "Female", "Nickelodeon", "Blonde competitive intellectual rival to Jimmy with yellow shirt who masks romantic interest through constant academic one-upmanship"),
    ("Timmy Turner", "Male", "Nickelodeon", "Buck-toothed ten-year-old in pink hat with fairy godparents granting wishes that inevitably go wrong due to Da Rules and personal impulsiveness"),
    ("Cosmo", "Male", "Nickelodeon", "Green-haired dim-witted fairy godfather with floating crown whose magical incompetence and childlike personality create constant wish complications"),
    ("Wanda", "Female", "Nickelodeon", "Pink-haired sensible fairy godmother with floating crown serving as voice of reason in godparent duo while genuinely caring for Timmy"),
    ("Vicky", "Female", "Nickelodeon", "Red-haired sadistic teenage babysitter in green shirt who torments children for pleasure and money representing Timmy's initial reason for needing fairies"),
    ("Denzel Crocker", "Male", "Nickelodeon", "Hunchbacked insane teacher with large ears and fairy-obsession constantly twitching while screaming FAIRY GODPARENTS to disprove his childhood theory"),
    ("Danny Phantom", "Male", "Nickelodeon", "White-haired teenage half-ghost hero in black and white jumpsuit fighting supernatural threats while balancing high school and secret identity"),
    ("Sam Manson", "Female", "Nickelodeon", "Goth best friend in black and purple with black hair and choker advocating vegetarianism and individuality while secretly crushing on Danny"),
    ("Tucker Foley", "Male", "Nickelodeon", "Tech-obsessed African-American best friend in yellow shirt and glasses with meat addiction and PDA enthusiasm providing tech support for ghost hunting"),
    ("Jazz Fenton", "Female", "Nickelodeon", "Older sister with long orange hair and psychology obsession who secretly knows Danny's secret while trying to support him through academic lens"),
    ("Zim", "Male", "Nickelodeon", "Tiny green alien with red eyes and no ears from Irken Empire on failed Earth conquest disguised in terrible human costume with wig"),
    ("GIR", "Male", "Nickelodeon", "Small blue malfunctioning robot assistant to Zim obsessed with tacos and TV wearing green dog costume as human disguise"),
    ("Dib Membrane", "Male", "Nickelodeon", "Paranormal-investigating boy with large head and black coat who alone recognizes Zim as alien while being dismissed as crazy by everyone"),
    ("Rocko", "Male", "Nickelodeon", "Australian-accented wallaby in blue shirt navigating surreal consumerist O-Town life as straight-man surrounded by weird neighbors and modern absurdities"),
    ("Heffer Wolfe", "Male", "Nickelodeon", "Obese yellow steer raised by wolves working dead-end jobs while being Rocko's gluttonous loyal best friend and roommate"),
    ("Filburt Shellbach", "Male", "Nickelodeon", "Anxious neurotic turtle in glasses with hypochondriac tendencies and catchphrase Oh fishsticks eventually marrying and having family"),
    ("Norbert Beaver", "Male", "Nickelodeon", "Older brother beaver with blonde pompadour and intellectual sarcasm constantly pulling younger brother into schemes while narrating journal entries"),
    ("Daggett Beaver", "Male", "Nickelodeon", "Younger brother beaver with brown hair and spastic personality speaking in third-person with nasal voice and obsession with action and adventure"),
    ("Cat", "Male", "Nickelodeon", "Conjoined orange feline twin attached to Dog on opposite side navigating shared body conflicts with erudite vocabulary and self-loathing"),
    ("Dog", "Male", "Nickelodeon", "Conjoined canine twin attached to Cat with simple-minded happiness chasing mailmen and cars while sharing body with intellectual opposite"),
    ("Eliza Thornberry", "Female", "Nickelodeon", "Red-haired twelve-year-old girl with braces and glasses who can talk to animals using magical power given by African shaman"),
    ("Darwin Thornberry", "Male", "Nickelodeon", "British-accented chimpanzee raised as Eliza's brother in nature-documentary family wearing striped shirt and acting as proper gentleman"),
    ("Donnie Thornberry", "Male", "Nickelodeon", "Feral adopted brother in shorts who communicates through gibberish grunts and destructive behavior raised by orangutans before family adoption"),
    ("Helga Pataki (Hey Arnold!)", "Female", "Nickelodeon", "Blonde unibrowed nine-year-old bully with pink dress aggressive exterior and secret shrine dedicated to obsessive love for Arnold including poetry"),
    ("Oblina", "Female", "Nickelodeon", "Black-and-white striped tall monster student with retractable limbs and prim proper personality training to scare humans alongside colleagues"),
    ("Ickis", "Male", "Nickelodeon", "Small red rabbit-like monster with big ears easily frightened and struggling with scare studies under strict Gromble at Monster Academy"),
    ("Krumm", "Male", "Nickelodeon", "Hairy round monster who holds his own eyeballs in hands possessing incredible stench-based scare techniques and loyal friendship with classmates"),
    ("Ren Hoek", "Male", "Nickelodeon", "Severely psychotic anxiety-ridden asthma-hound chihuahua with elongated snout prone to violent outbursts and mental breakdowns alongside dim friend"),
    ("Stimpy", "Male", "Nickelodeon", "Overweight dim-witted pink cat with blue nose and brain the size of peanut obsessed with Gritty Kitty litter and pressing red shiny button"),
    ("Dora the Explorer", "Female", "Nick Jr.", "Cheerful bilingual seven-year-old Latina girl with brown bob haircut and pink shirt who interacts directly with viewers to solve navigational puzzles"),
    ("Boots", "Male", "Nick Jr.", "Monkey companion to Dora wearing red boots communicating enthusiastically and helping solve puzzles while climbing and performing acrobatics"),
    ("Swiper", "Male", "Nick Jr.", "Orange fox wearing blue mask and gloves who attempts to steal items requiring audience interaction to chant Swiper no swiping three times"),
    ("Blue", "Female", "Nick Jr.", "Bright blue-spotted puppy who communicates through expressive barks and leaves three distinct paw-print clues around environment to signal thoughts"),
    ("Steve", "Male", "Nick Jr.", "Green-striped shirt host of Blue's Clues interacting with animated world using handy-dandy notebook to draw and solve Blue's paw-print clues"),
    ("Josh", "Male", "Nick Jr.", "Reboot host of Blue's Clues and You continuing Steve and Joe's legacy with smartphone-based clues and youthful energetic approach to puzzle-solving"),
    ("PAW Patrol - Ryder", "Male", "Nick Jr.", "Ten-year-old human leader of rescue pups in red vest coordinating missions using Pup-Pad and ATV to protect Adventure Bay community"),
    ("Chase", "Male", "Nick Jr.", "German shepherd police pup in blue uniform with megaphone dealing with spy and traffic missions while allergic to cats and feathers"),
    ("Marshall", "Male", "Nick Jr.", "Dalmatian firefighting pup in red helmet known for clumsy accidents and water cannon skills while serving as comic relief of PAW Patrol"),
    ("Skye", "Female", "Nick Jr.", "Cockapoo aviation pup in pink flight goggles piloting helicopter with wings and catchphrase This pups gotta fly during aerial rescues"),
    ("Rubble", "Male", "Nick Jr.", "English bulldog construction pup in yellow hard hat operating bulldozer and skateboard with love of food and catchphrase Rubble on the double"),
    ("Rocky", "Male", "Nick Jr.", "Mixed-breed recycling pup in green using repurposed items from backpack to fix problems with catchphrase Don't lose it reuse it"),
    ("Zuma", "Male", "Nick Jr.", "Chocolate Labrador water rescue pup in orange operating hovercraft and loving surfing culture with catchphrase Let's dive in"),
    ("Everest", "Female", "Nick Jr.", "Husky mountain rescue pup in teal with snowplow operator responding to snowy emergencies with catchphrase Ice or snow I'm ready to go"),
    ("Tracker", "Male", "Nick Jr.", "Chihuahua jungle rescue pup in brown with excellent hearing operating jeep through jungle terrain speaking Spanish phrases and catchphrase I'm all ears"),

    # ====================
    # Disney Channel / Disney Junior / Disney XD
    # ====================
    ("Kim Possible", "Female", "Disney Channel", "Confident athletic high school cheerleader and global secret agent with flowing red hair wearing signature black crop top and green cargo pants"),
    ("Ron Stoppable", "Male", "Disney Channel", "Blonde awkward sidekick with freckles and pet naked mole rat Rufus providing comic relief while occasionally saving the day despite incompetence"),
    ("Rufus", "Male", "Disney Channel", "Pink naked mole rat and Ron's loyal pocket companion with surprising intelligence and ability to operate complex machinery despite rodent size"),
    ("Wade", "Male", "Disney Channel", "Ten-year-old African-American genius operating mission support from bedroom via Kimmunicator gadget designing all of Kim's spy equipment and technology"),
    ("Dr. Drakken", "Male", "Disney Channel", "Blue-skinned mad scientist with scar and lab coat constantly attempting world domination with elaborate schemes inevitably foiled by Kim"),
    ("Shego", "Female", "Disney Channel", "Green-pale-skinned sarcastic sidekick to Drakken with plasma energy powers and dark wit formerly hero turned mercenary villain"),
    ("Phineas Flynn", "Male", "Disney Channel", "Triangular-headed inventive stepbrother in striped shirt building impossible backyard constructions during summer vacation with boundless optimism"),
    ("Ferb Fletcher", "Male", "Disney Channel", "Green-haired tall silent stepbrother of Phineas speaking only once per episode while matching brother's engineering genius through action"),
    ("Candace Flynn", "Female", "Disney Channel", "Red-haired teenage sister obsessively trying to bust brothers by showing Mom their elaborate inventions but always failing at last moment"),
    ("Perry the Platypus", "Male", "Disney Channel", "Teal semi-aquatic secret agent monotreme wearing fedora engaging in silent spy battles against evil Dr. Doofenshmirtz while disguised as mindless pet"),
    ("Dr. Doofenshmirtz", "Male", "Disney Channel", "Lanky failed mad scientist with tragic backstory operating inators to wreak minor havoc on Tri-State Area while being surprisingly sympathetic father"),
    ("Dipper Pines", "Male", "Disney Channel", "Twelve-year-old boy in blue pine tree cap investigating supernatural mysteries of Gravity Falls through journal while navigating summer twin adventures"),
    ("Mabel Pines", "Female", "Disney Channel", "Eccentric sweater-wearing twin sister with braces and grappling hook obsessed with cute things and boy bands bringing chaotic optimism to mystery-solving"),
    ("Stan Pines (Grunkle Stan)", "Male", "Disney Channel", "Fez-wearing con-artist great-uncle running Mystery Shack tourist trap with gruff exterior hiding deeper secrets including portal-building past"),
    ("Soos Ramirez", "Male", "Disney Channel", "Overweight loyal handyman in green shirt with infinite wisdom wrapped in simple-minded delivery serving as Pines family's most reliable ally"),
    ("Wendy Corduroy", "Female", "Disney Channel", "Tall laid-back red-haired lumberjack teen cashier in green flannel cap representing cool older teen archetype and Dipper's unrequited crush"),
    ("Bill Cipher", "Male", "Disney Channel", "Triangular one-eyed dream demon in top hat from second dimension seeking to bring weirdmageddon reality-bending chaos to physical world"),
    ("Star Butterfly", "Female", "Disney Channel", "Magical princess from Mewni with blonde hair and heart-shaped cheek marks wielding dimensional scissors and chaotic wand combat style"),
    ("Marco Diaz", "Male", "Disney Channel", "Red-hoodied safe-kid turned interdimensional warrior through martial arts training and friendship with Star developing confidence and combat skills"),
    ("Luz Noceda", "Female", "Disney Channel", "Afro-Latina teenage girl in purple and white cat hoodie who discovers portal to Boiling Isles and trains as witch despite lacking innate magic"),
    ("Eda the Owl Lady", "Female", "Disney Channel", "Grey-maned wanted witch with gold fang and cursed owl-beast form serving as reluctant mentor and surrogate mother to Luz"),
    ("King", "Male", "Disney Channel", "Small skull-headed demon with broken horn living with Eda believing himself former king of demons while actually being infant Titan"),
    ("Anne Boonchuy", "Female", "Disney Channel", "Thai-American teenage girl transported to frog-filled Amphibia wearing school uniform who learns survival skills and community values"),
    ("Sprig Plantar", "Male", "Disney Channel", "Small pink energetic frog with orange hair and boundless enthusiasm serving as Anne's first true friend and loyal adventure companion"),
    ("Hop Pop Plantar", "Male", "Disney Channel", "Elderly orange frog patriarch with tuft of white hair farming produce and dispensing old-fashioned wisdom with surprising dramatic talent"),
    ("Polly Plantar", "Female", "Disney Channel", "Purple infant frog tadpole in bucket carrying extreme violent tendencies hidden behind cute appearance eventually gaining legs"),
    ("Mickey Mouse", "Male", "Disney Junior", "Iconic cheerful mouse in red shorts and yellow shoes with high-pitched optimistic voice serving as face of entire Disney brand"),
    ("Minnie Mouse", "Female", "Disney Junior", "Female counterpart to Mickey in polka-dot dress and bow with feminine kind personality and identical mouse design in different clothing"),
    ("Donald Duck", "Male", "Disney Junior", "White duck in blue sailor suit with severe anger issues and unintelligible speech providing comedic frustration across all Disney media"),
    ("Daisy Duck", "Female", "Disney Junior", "Donald's girlfriend duck in purple with bow and sassy personality matching his energy while maintaining sophisticated charm"),
    ("Goofy", "Male", "Disney Junior", "Tall lanky anthropomorphic dog with distinctive laugh and clumsy personality in orange turtleneck and blue pants serving as everyman character"),
    ("Pluto", "Male", "Disney Junior", "Orange pet dog of Mickey who walks on all fours unlike Goofy communicating through barks while causing accidental chaos"),
    ("Sofia the First", "Female", "Disney Junior", "Young girl with brown hair who becomes princess through mother's marriage to king wearing purple dress and amulet that grants magical assistance"),
    ("Doc McStuffins", "Female", "Disney Junior", "African-American six-year-old aspiring veterinarian with magic stethoscope bringing toys to life and operating backyard clinic for stuffed animals"),
    ("Vampirina", "Female", "Disney Junior", "Friendly purple vampire girl from Transylvania adjusting to human Pennsylvania life with ghostly family and monster friends"),
    ("Jake (Never Land Pirates)", "Male", "Disney Junior", "Young pirate captain in blue bandana and vest leading crew on treasure hunts while outwitting Captain Hook with teamwork and gold doubloons"),
    ("Miles (Tomorrowland)", "Male", "Disney Junior", "Space-traveling boy with blue hair exploring galaxy on starship with family introducing STEM concepts through interstellar adventure missions"),
    ("Fancy Nancy", "Female", "Disney Junior", "Red-curly-haired girl obsessed with all things fancy using sophisticated French vocabulary while teaching elegance and self-expression"),
    ("Puppy Dog Pals - Bingo", "Male", "Disney Junior", "Pug puppy in blue collar embarking on neighborhood missions with brother Rolly to help their human Bob using creative problem-solving"),
    ("Rolly", "Male", "Disney Junior", "Pug puppy in red collar and Bingo's brother known for insatiable appetite and tendency to eat things before thinking during dog adventures"),
    ("Mira (Royal Detective)", "Female", "Disney Junior", "Indian-inspired young girl detective in orange serving as royal investigator solving mysteries in Jalpur with mongoose companions"),
    ("T.O.T.S. - Pip", "Male", "Disney Junior", "Small penguin delivery bird in blue transporting baby animals to families with partner Freddy learning teamwork and nurturing skills"),
    ("Freddy (T.O.T.S.)", "Male", "Disney Junior", "Tall flamingo co-delivery bird with nervous personality learning confidence while transporting baby animals through aerial delivery service"),
    ("Bluey", "Female", "Disney Junior", "Six-year-old Blue Heeler puppy in blue with boundless imagination and energy turning everyday family moments into elaborate creative games"),
    ("Bingo (Bluey)", "Female", "Disney Junior", "Four-year-old younger sister Blue Heeler puppy in orange serving as playmate and companion to Bluey with gentle sensitive personality"),
    ("Bandit Heeler", "Male", "Disney Junior", "Blue Heeler father archaeologist who commits fully to daughters' imaginative games with remarkable patience humor and occasional dad-jokes"),
    ("Chilli Heeler", "Female", "Disney Junior", "Red Heeler mother working airport security balancing career with parenting while participating in family games with warm nurturing approach"),

    # ====================
    # PBS Kids
    # ====================
    ("Arthur Read", "Male", "PBS Kids", "Intellectual soft-spoken eight-year-old anthropomorphic aardvark wearing round yellow-rimmed glasses yellow sweater and jeans navigating childhood social dynamics"),
    ("D.W. Read", "Female", "PBS Kids", "Arthur's bratty four-year-old sister in pink dress and white shirt with bobbed hair causing constant irritation while occasionally showing hidden sweetness"),
    ("Buster Baxter", "Male", "PBS Kids", "Arthur's rabbit best friend with blue jacket and glasses obsessed with aliens food and Bionic Bunny while dealing with divorced parents"),
    ("Francine Frensky", "Female", "PBS Kids", "Competitive tomboy monkey with brown hair and red jacket excelling in sports while learning lessons about teamwork and humility"),
    ("Muffy Crosswire", "Female", "PBS Kids", "Rich spoiled monkey girl with purple dress and blonde hair whose father owns car dealership learning about privilege and genuine friendship"),
    ("Brain (Alan Powers)", "Male", "PBS Kids", "African-American bear with glasses and genius intellect running ice cream shop while providing academic assistance and explanations to friends"),
    ("Binky Barnes", "Male", "PBS Kids", "Large bulldog initially presented as bully but revealed to have soft side including love of ballet clarinet and peonies"),
    ("Mr. Ratburn", "Male", "PBS Kids", "Third-grade teacher rat in suit with demanding reputation later revealed to be happily married to another man in landmark representation episode"),
    ("Sue Ellen Armstrong", "Female", "PBS Kids", "Well-traveled cat with red hair and global experiences bringing diverse cultural perspective and martial arts skills to Elwood City"),
    ("Curious George", "Male", "PBS Kids", "Small brown monkey with insatiable curiosity who doesn't speak but causes well-intentioned chaotic situations requiring Man with Yellow Hat's rescue"),
    ("Man with the Yellow Hat", "Male", "PBS Kids", "Tall unnamed human caretaker in yellow suit and hat with infinite patience for monkey companion's antics and urban zoo keeper background"),
    ("Daniel Tiger", "Male", "PBS Kids", "Anthropomorphic young tiger in red sweater and sneakers direct descendant of Mister Rogers' Neighborhood teaching emotional literacy to preschoolers"),
    ("Katerina Kittycat", "Female", "PBS Kids", "Pink cat friend of Daniel Tiger who dances when excited learning social skills alongside tiger companion in Neighborhood of Make-Believe"),
    ("O the Owl", "Male", "PBS Kids", "Blue owl with book obsession living in tree providing factual information and learning emotional vocabulary in Daniel Tiger's neighborhood"),
    ("Xavier Riddle", "Male", "PBS Kids", "Curious boy in red sweater traveling through time via secret museum to meet historical figures learning about their childhood experiences"),
    ("Molly Mabray", "Female", "PBS Kids", "Alaska Native girl with braided hair living in small town who vlogs about daily life while exploring wilderness and cultural traditions"),
    ("Wild Kratts - Chris Kratt", "Male", "PBS Kids", "Green-suited animated version of real zoologist using creature power suits to transform into animals for wildlife adventure education"),
    ("Martin Kratt", "Male", "PBS Kids", "Blue-suited older Kratt brother with creature adventure knowledge leading wildlife rescue missions through animal transformation technology"),
    ("Super Why - Whyatt", "Male", "PBS Kids", "Green-caped superhero reader with glasses who solves problems by entering storybooks and changing narratives through spelling and reading skills"),
    ("Elmo", "Male", "PBS Kids", "Small red furry monster from Sesame Street with high-pitched voice speaking in third person obsessed with tickles and learning"),
    ("Big Bird", "Male", "PBS Kids", "Eight-foot-tall yellow bird with distinctively childlike wonder living on Sesame Street asking curious questions about world around him"),
    ("Cookie Monster", "Male", "PBS Kids", "Blue furry monster with googly eyes and insatiable cookie appetite who has learned about sometimes foods through self-control lessons"),
    ("Oscar the Grouch", "Male", "PBS Kids", "Green furry grouch living in trash can with pet worm Slimey who paradoxically loves filth and expresses happiness through complaining"),

    # ====================
    # Fox Kids / Jetix / Kids' WB
    # ====================
    ("Ash Ketchum", "Male", "Kids' WB", "Ten-year-old Pokémon trainer in blue jacket and red cap from Pallet Town traveling regions with Pikachu aspiring to become Pokémon Master"),
    ("Pikachu", "Male", "Kids' WB", "Small yellow electric mouse Pokémon with red cheeks serving as Ash's best friend and most loyal partner refusing evolution into Pokéball"),
    ("Misty", "Female", "Kids' WB", "Orange-haired Water-type gym leader and companion with short temper and fear of Bug-types carrying signature Togepi early in journey"),
    ("Brock", "Male", "Kids' WB", "Spiky-haired Pokémon breeder and Rock-type specialist who falls in love with every woman while cooking and caring for traveling group"),
    ("Team Rocket - Jessie", "Female", "Kids' WB", "Magenta-haired villain in white uniform alongside James and Meowth constantly attempting to steal Pikachu through elaborate disguises"),
    ("James", "Male", "Kids' WB", "Blue-haired wealthy runaway villain in white uniform with effeminate presentation and tragic rich-kid backstory alongside partner Jessie"),
    ("Meowth (Team Rocket)", "Male", "Kids' WB", "Talking Scratch Cat Pokémon who learned human speech and bipedalism to impress female Meowth now serving Team Rocket trio"),
    ("Yugi Moto", "Male", "Kids' WB", "Spiky-haired teenage boy who solves ancient Millennium Puzzle awakening spirit of pharaoh and ability to challenge opponents to Shadow Games"),
    ("Seto Kaiba", "Male", "Kids' WB", "Tall wealthy CEO teenager in long white coat with dragon obsession and rivalry against Yugi using Blue-Eyes White Dragon deck"),
    ("Batman (Animated Series)", "Male", "Kids' WB", "Dark Knight vigilante in grey and black with cape protecting Gotham City through detective work and martial prowess in animated DC universe"),
    ("Superman (Animated)", "Male", "Kids' WB", "Red-caped Kryptonian hero in blue tights defending Metropolis with flight strength and heat vision as moral symbol of hope"),
    ("Bugs Bunny", "Male", "Fox Kids", "Clever grey hare with Brooklyn accent and carrot-chewing habit outwitting opponents through cross-dressing disguises and witty banter"),
    ("Power Rangers - Red Ranger", "Male", "Fox Kids", "Helmeted spandex-suited teenager leading color-coded martial arts team piloting combining Megazord against giant monster threats"),
    ("Digimon - Agumon", "Male", "Fox Kids", "Orange dinosaur Digimon partner to Tai capable of digivolving into Greymon and beyond through bond of courage and friendship"),
    ("Tai Kamiya", "Male", "Fox Kids", "Goggle-wearing leader of DigiDestined with brown spiky hair and Crest of Courage guiding team through Digital World dangers"),
    ("Bobby Hill", "Male", "Fox Kids", "Overweight sensitive preteen son of Hank Hill with narrow eyes and struggling athletic ability often showing surprising wisdom"),
    ("Spider-Man (Animated)", "Male", "Fox Kids", "Red and blue web-slinging teenage hero balancing high school with crime-fighting and great responsibility mantra in animated series"),
    ("X-Men - Wolverine", "Male", "Fox Kids", "Short adamantium-clawed mutant with yellow and blue costume gruff cigar-chomping personality and berserker rage in animated adaptation"),
    ("Cyclops", "Male", "Fox Kids", "Ruby-quartz visored field leader of X-Men projecting optic blasts while maintaining strict leadership and romantic tension with Jean Grey"),
    ("Storm", "Female", "Fox Kids", "White-haired African weather-controlling mutant goddess with white costume speaking dramatically while summoning lightning and wind"),
    ("Beast Boy", "Male", "Kids' WB", "Green-skinned shape-shifting teenager who transforms into any animal while cracking jokes in Teen Titans animated series"),
    ("Raven", "Female", "Kids' WB", "Violet-haired half-demon empath in dark cloak who suppresses emotions to prevent demonic father Trigon from destroying world"),
    ("Starfire", "Female", "Kids' WB", "Orange-skinned Tamaranean princess with red hair and green eyes learning Earth customs while projecting star-bolts and super-strength"),
    ("Cyborg (Teen Titans)", "Male", "Kids' WB", "Half-robot half-human teen with blue circuitry and sonic cannon arm shouting Booyah while grappling with mechanical body and humanity"),
    ("Robin (Teen Titans)", "Male", "Kids' WB", "Masked acrobatic leader of Teen Titans with red and green costume and staff fighting without powers while hiding Batman connection"),

    # ====================
    # Disney+ / Hulu / Netflix Originals
    # ====================
    ("Grogu (The Child / Baby Yoda)", "Male", "Disney+", "Small green Force-sensitive alien of Yoda's species with large ears and eyes communicating through coos while using limited Force abilities"),
    ("Luca Paguro", "Male", "Disney+", "Young sea monster boy with blue scales who transforms to human on land exploring Italian Riviera friendship while hiding true identity"),
    ("Alberto Scorfano", "Male", "Disney+", "Confident orphaned sea monster with green scales and Vespa obsession living alone on island becoming Luca's first friend and adventure catalyst"),
    ("Ian Lightfoot", "Male", "Disney+", "Blue elf teenager in plaid shirt lacking confidence who discovers magic inheritance while questing to spend one day with deceased father"),
    ("Barley Lightfoot", "Male", "Disney+", "Larger blue elf older brother with mullet and D&D-style quest obsession providing unexpected wisdom and selfless support to anxious brother"),
    ("Mirabel Madrigal", "Female", "Disney+", "Green-glasses-wearing non-magical daughter in magical family wearing embroidered dress who must save miracle despite lacking gift"),
    ("Hilda", "Female", "Netflix", "Blue-haired adventurous girl in red scarf and boots living between wilderness and city befriending trolls giants and magical creatures"),
    ("Kipo Oak", "Female", "Netflix", "Dark-skinned teenage girl with purple cat genes exploring post-apocalyptic surface world filled with mutant animals while discovering pacifist solutions"),
    ("Castlevania - Trevor Belmont", "Male", "Netflix", "Scarred whip-wielding monster hunter in dark clothing and cloak representing fallen Belmont clan protecting Wallachia from Dracula's demon army"),
    ("Sypha Belnades", "Female", "Netflix", "Blonde Speaker magician in blue robes wielding elemental fire ice and lightning magic while serving as brains of monster-hunting trio"),
    ("Alucard", "Male", "Netflix", "Long-haired half-vampire son of Dracula with golden eyes and floating sword fighting against father to protect humanity from genocide"),
    ("She-Ra - Adora", "Female", "Netflix", "Blonde tall warrior formerly Horde soldier who discovers magical sword transforming her into eight-foot-tall princess champion of Etheria"),
    ("Catra", "Female", "Netflix", "Cat-eared feline Horde soldier with heterochromatic eyes and complex romantic tension with Adora navigating redemption through abusive upbringing"),
    ("Glimmer", "Female", "Netflix", "Short sparkly-haired princess with teleportation powers and pink color scheme serving as rebellion leader alongside Adora and Bow"),
    ("The Dragon Prince - Callum", "Male", "Netflix", "Brown-haired step-prince and mage in blue jacket who connects to sky primal magic becoming first human mage in centuries"),
    ("Rayla", "Female", "Netflix", "White-haired Moonshadow elf assassin with Scottish accent and twin blades who rejects killing to protect dragon egg alongside human allies"),

    # ====================
    # MeTV / Retro TV / Antenna TV / Turner Classic
    # ====================
    ("George Jetson", "Male", "MeTV", "Space-age father with red hair working short hours at Spacely Sprockets pushing buttons while navigating futuristic family sitcom life"),
    ("Jane Jetson", "Female", "MeTV", "White-haired futuristic housewife in purple dress managing household with robotic maid Rosey while spending husband's money at space malls"),
    ("Judy Jetson", "Female", "MeTV", "Teenage daughter with blonde ponytail and space-age fashion obsessed with boys and music while dealing with typical adolescent concerns"),
    ("Elroy Jetson", "Male", "MeTV", "Boy genius son with spiky brown hair attending space elementary school and building advanced robots and gadgets"),
    ("Astro", "Male", "MeTV", "Talking blue dog of Jetson family who speaks with R-starting words and expresses extreme loyalty to Elroy"),
    ("Yogi Bear", "Male", "Turner Classic Cartoon blocks", "Green-hatted park-dwelling bear with collar and tie who steals picnic baskets while outsmarting Ranger Smith with catchphrase smarter than average"),
    ("Boo-Boo Bear", "Male", "Turner Classic Cartoon blocks", "Small brown bear companion to Yogi wearing purple bow tie serving as conscience and voice of reason in picnic-stealing schemes"),
    ("Huckleberry Hound", "Male", "Turner Classic Cartoon blocks", "Blue anthropomorphic dog in hat and collar with Southern drawl working various jobs while singing My Darling Clementine"),
    ("Quick Draw McGraw", "Male", "Turner Classic Cartoon blocks", "White horse sheriff with Western drawl who often assumes secret identity El Kabong hitting villains with guitar"),
    ("Snagglepuss", "Male", "Turner Classic Cartoon blocks", "Pink mountain lion with collar and cuffs speaking in theatrical Shakespearean cadence with catchphrase Heavens to Murgatroyd"),
    ("Magilla Gorilla", "Male", "Turner Classic Cartoon blocks", "Large gorilla with hat and tie sitting in pet shop window priced permanently on sale while getting into gentle misadventures"),
    ("Wally Gator", "Male", "Turner Classic Cartoon blocks", "Green alligator wearing collar and hat living in zoo attempting escapes while being returned by zookeeper Mr. Twiddle"),
    ("Top Cat", "Male", "Turner Classic Cartoon blocks", "Yellow-furred alley cat with purple vest and hat leading gang of Manhattan cats in get-rich-quick schemes against Officer Dibble"),
    ("George of the Jungle", "Male", "Turner Classic Cartoon blocks", "Muscular vine-swinging Tarzan parody who constantly crashes into trees while protecting jungle with catchphrase Watch out for that tree"),
    ("Mighty Mouse", "Male", "Turner Classic Cartoon blocks", "Small super-powered mouse in red and yellow costume with cape flying in to save the day with operatic theme song"),
    ("Underdog", "Male", "Turner Classic Cartoon blocks", "Humble shoeshine dog who transforms into caped superhero speaking in rhymes while rescuing Sweet Polly Purebred"),
    ("Rocky the Flying Squirrel", "Male", "Turner Classic Cartoon blocks", "Brown aviator-cap-wearing squirrel sidekick to Bullwinkle navigating Cold War espionage adventures with cheerful can-do attitude"),
    ("Bullwinkle J. Moose", "Male", "Turner Classic Cartoon blocks", "Dim-witted antlered moose with huge nose and perpetual optimism stumbling through international spy plots with terrible pun delivery"),

    # ====================
    # Boomerang / Cartoonito / Discovery Family
    # ====================
    ("Scooby-Doo", "Male", "Boomerang", "Large cowardly brown Great Dane with black spots speaking broken English intensely motivated by Scooby Snacks and loyal to mystery crew"),
    ("Shaggy Rogers", "Male", "Boomerang", "Tall lanky beatnik in green shirt and brown pants with enormous appetite and cowardly disposition paired with Scooby as comic relief"),
    ("Fred Jones", "Male", "Boomerang", "Blonde ascot-wearing leader of Mystery Inc driving Mystery Machine and setting elaborate traps often splitting up the gang"),
    ("Daphne Blake", "Female", "Boomerang", "Red-haired fashionable member of Mystery Inc in purple dress and green scarf prone to danger and being captured"),
    ("Velma Dinkley", "Female", "Boomerang", "Short orange-turtlenecked bespectacled brains of Mystery Inc solving mysteries through deduction while frequently losing glasses"),
    ("Tom Cat", "Male", "Boomerang", "Blue-grey shorthair cat with white paws fiercely determined and physically expressive driven by perpetual chaotic instinct to catch mouse"),
    ("Jerry Mouse", "Male", "Boomerang", "Small brown highly resourceful house mouse with large ears and cheerful disposition possessing extreme tactical intelligence"),
    ("Bugs Bunny", "Male", "Boomerang (brand)", "Clever grey hare with Brooklyn accent carrot-chewing habit and cross-dressing trickster mastery of cartoon logic"),
    ("Daffy Duck", "Male", "Boomerang (brand)", "Hyperactive black duck with white neck-ring and lisp driven by frustrated spotlight-seeking personality"),
    ("Porky Pig", "Male", "Boomerang (brand)", "Mild-mannered stuttering pink pig in blue jacket and red bowtie serving as classic straight-man to chaos"),
    ("Elmer Fudd", "Male", "Boomerang (brand)", "Bald hunting-cap-wearing hunter with speech impediment perpetually pursuing wabbits with shotgun while being outsmarted"),
    ("Tweety Bird", "Male", "Boomerang (brand)", "Small yellow canary with large blue eyes and high-pitched voice who secretly viciously outsmarts predator Sylvester"),
    ("Sylvester the Cat", "Male", "Boomerang (brand)", "Black and white tuxedo cat with lisp obsessed with eating Tweety while suffering pain and humiliation"),
    ("Tasmanian Devil (Taz)", "Male", "Boomerang (brand)", "Brown whirlwind-spinning marsupial with enormous appetite communicating through growls and destroying everything in path"),
    ("Foghorn Leghorn", "Male", "Boomerang (brand)", "Large white rooster with Southern drawl and catchphrase I say boy delivering long-winded monologues while pranking Barnyard Dog"),
    ("Road Runner", "Male", "Boomerang (brand)", "Purple-blue fast-running bird with crest who only says Beep Beep while effortlessly evading Wile E. Coyote's ACME traps"),
    ("Wile E. Coyote", "Male", "Boomerang (brand)", "Brown scrawny predator who orders endless ACME products from catalog only to have them backfire spectacularly against Road Runner"),
    ("Pepe Le Pew", "Male", "Boomerang (brand)", "French-accented skunk hopeless romantic who pursues female cat mistaking white stripe for skunk while being oblivious to own odor"),
    ("Marvin the Martian", "Male", "Boomerang (brand)", "Small black Martian in Roman helmet and skirt speaking softly while attempting to destroy Earth with Illudium Q-36 Explosive Space Modulator"),
    ("The Flintstones - Barney Rubble", "Male", "Boomerang", "Short blonde caveman neighbor and best friend to Fred working in same quarry with cheerful loyal personality and infectious laugh"),
    ("Betty Rubble", "Female", "Boomerang", "Blonde cavewoman wife of Barney with blue dress and supportive personality contrasted with Wilma's more assertive nature"),
    ("Wilma Flintstone", "Female", "Boomerang", "Red-haired cavewoman wife in white dress and pearl necklace holding family together despite Fred's schemes and temper"),
    ("Pebbles Flintstone", "Female", "Boomerang", "Infant daughter of Fred and Wilma with red hair in ponytail and bone hair clip eventually becoming teenage character"),
    ("Bamm-Bamm Rubble", "Male", "Boomerang", "Super-strong adopted infant son of Barney and Betty wearing fur diaper and carrying club with signature yell"),
    ("Space Ghost (Classic)", "Male", "Boomerang", "White-cowled intergalactic superhero in yellow cape with power bands projecting various rays fighting villains in original 1960s series"),
    ("Jonny Quest", "Male", "Boomerang", "Blonde adventurous boy in black t-shirt accompanying scientist father on globe-trotting investigations fighting villains and monsters"),
    ("Hadji", "Male", "Boomerang", "Indian adopted brother of Jonny Quest in turban using mystic knowledge and street smarts to assist Quest team adventures"),
    ("Birdman", "Male", "Boomerang", "Winged superhero absorbing solar energy with feathered costume and bird companion Avenger fighting villains as agent of government"),
    ("The Herculoids - Zandor", "Male", "Boomerang", "Tarzan-like warrior protecting planet Quasar with family of bizarre creatures including rock-ape dragon and energy-shooting beings"),
    ("Jabberjaw", "Male", "Boomerang", "Great white shark who talks like Curly from Three Stooges playing drums in underwater rock band solving mysteries in 2076"),
    ("Captain Caveman", "Male", "Boomerang", "Short hairy super-powered caveman superhero thawed from ice who shouts Captain CAAAAAVEMAN while pulling gadgets from fur"),
    ("Batman (Bat-Mite)", "Male", "Boomerang", "Imp-like interdimensional being in miniature Batman costume who idolizes Dark Knight while causing magical chaos in classic comics"),
    ("Shazzan", "Male", "Boomerang", "Fifty-foot genie summoned by twin siblings through magic ring capable of granting wishes and defeating Arabian-themed villains"),

    # ====================
    # Universal Kids / Sprout / Qubo
    # ====================
    ("Barney", "Male", "Universal Kids", "Purple anthropomorphic Tyrannosaurus rex who teaches children through song and dance with group of multicultural child friends"),
    ("Bob the Tomato", "Male", "Qubo", "Round bright red highly articulate tomato serving as structured sensible host of educational patch focusing on moral and storytelling lessons"),
    ("Larry the Cucumber", "Male", "Qubo", "Tall green cucumber with goofy personality and silly songs serving as Bob's foil in VeggieTales biblical and moral storytelling"),
    ("Thomas the Tank Engine", "Male", "Universal Kids", "Blue anthropomorphic steam locomotive with numbered tender and cheerful face learning lessons about usefulness on Island of Sodor"),
    ("Percy the Small Engine", "Male", "Universal Kids", "Green small saddle tank engine and Thomas's best friend known for cheeky personality and occasional accidents"),
    ("Peppa Pig", "Female", "Universal Kids", "Bossy four-year-old pink pig in red dress with tendency to snort and jump in muddy puddles with family and friends"),
    ("George Pig", "Male", "Universal Kids", "Two-year-old blue-shirted pig brother of Peppa who speaks in single words obsessed with his toy dinosaur Mr. Dinosaur"),
    ("Curious George (Universal)", "Male", "Universal Kids", "Small brown monkey with insatiable curiosity causing well-intentioned chaos requiring Man with Yellow Hat's constant rescue"),
    ("Caillou", "Male", "Universal Kids", "Bald four-year-old boy in yellow shirt with whiny personality navigating childhood while learning life lessons from parents"),
    ("Teletubbies - Tinky Winky", "Male", "Universal Kids", "Purple largest Teletubby with triangular antenna and red handbag living in surreal dome landscape communicating through baby talk"),
    ("Dipsy", "Male", "Universal Kids", "Green Teletubby with straight antenna and black-and-white fur hat known for stubborn personality and signature dip dance"),
    ("Laa-Laa", "Female", "Universal Kids", "Yellow Teletubby with curly antenna who loves to sing and dance while carrying favorite orange ball"),
    ("Po", "Female", "Universal Kids", "Red smallest Teletubby with circle antenna riding scooter while communicating through Po sounds and giggling"),
    ("Jay Jay the Jet Plane", "Male", "Universal Kids", "Small blue jet plane with face and childlike curiosity learning about science and friendship through flight adventures"),
    ("Kipper the Dog", "Male", "Universal Kids", "Warm-hearted orange dog with British accent and gentle personality exploring everyday adventures with animal friends"),
    ("Fireman Sam", "Male", "Universal Kids", "Welsh firefighter with blue uniform and helmet protecting Pontypandy village while teaching fire safety to children"),
    ("Postman Pat", "Male", "Universal Kids", "Friendly postman with glasses and red van delivering mail in Greendale village accompanied by black-and-white cat Jess"),
    ("Bob the Builder", "Male", "Universal Kids", "Cheerful construction worker in yellow hard hat and overalls with catchphrase Can we fix it solving problems with talking machines"),
    ("Chloe (Chloe's Closet)", "Female", "Universal Kids", "Imaginative young girl with blonde hair who discovers magical dress-up adventures through closet portal with animal friends"),
    ("Zoboomafoo", "Male", "Universal Kids", "Real lemur puppet hybrid named Zoboo who greets Kratt brothers at Animal Junction exploring wildlife with cheerful energy"),

    # ====================
    # FX / FXX / TBS / HBO / Max
    # ====================
    ("Sterling Archer", "Male", "FXX", "Handsome narcissistic black-haired secret agent in immaculate grey tactical turtleneck possessing high tactical reflexes offset by extreme hedonism"),
    ("Lana Kane", "Female", "FXX", "Tall dark-skinned secret agent with enormous hands serving as Archer's ex and mother of his child wielding twin Tec-9s competently"),
    ("Pam Poovey", "Female", "FXX", "Overweight HR director turned field agent with dolphin tattoo and drift-racing skills revealed to have surprisingly violent underground past"),
    ("Cheryl Tunt", "Female", "FXX", "Wealthy insane billionaire secretary with choking fetish and multiple personalities who funds agency while being completely unstable"),
    ("Stan Smith", "Male", "TBS", "Square-jawed aggressively patriotic CIA officer with massive chin wearing sharp blue suit deeply set in rigid national defense values"),
    ("Francine Smith", "Female", "TBS", "Blonde housewife with bobbed hair and suburban style who secretly parties hard and engages in increasingly unhinged behavior"),
    ("Steve Smith", "Male", "TBS", "Nerdy teenage son with red hair and glasses aspiring to popularity while possessing surprising musical talent and hormonal desperation"),
    ("Roger the Alien", "Male", "TBS", "Grey sarcastic alien with hundreds of personas and costumes living in Smith attic drinking heavily while causing psychological chaos"),
    ("Klaus", "Male", "TBS", "German-accented goldfish with human brain in fish bowl perpetually lusting after Francine while being bullied by entire family"),
    ("Futurama - Fry", "Male", "TBS", "Red-haired dim-witted pizza delivery boy from 1999 cryogenically frozen to year 3000 wearing red jacket and navigating future alongside robot and cyclops"),
    ("Leela", "Female", "TBS", "Purple-haired one-eyed mutant spaceship captain with wrist-mounted weapons confident piloting skills and search for true alien origins"),
    ("Bender Bending Rodriguez", "Male", "TBS", "Alcoholic cigar-smoking kleptomaniac bending robot with catchphrase Bite my shiny metal ass serving as Fry's best friend"),
    ("Professor Farnsworth", "Male", "TBS", "Ancient bald mad scientist with thick glasses running Planet Express delivery company inventing doomsday devices and declaring Good news everyone"),
    ("Game of Thrones (Animated) - Dragon", "Male", "HBO", "Fire-breathing reptilian beast with scales and membranous wings capable of devastating cities and forming telepathic bonds with Targaryen riders"),
    ("Rick Sanchez (HBO Max)", "Male", "Max", "Cynical genius alcoholic mad scientist with wild grey-blue hair and lab coat utilizing interdimensional technology with emotional detachment"),
    ("Harley Quinn (Animated Series)", "Female", "Max", "Bleach-skinned jester-costumed antihero with pigtails and baseball bat breaking up with Joker to form own villain crew with foul-mouthed comedy"),
    ("Poison Ivy", "Female", "Max", "Green-skinned red-haired eco-terrorist and botanist with plant-control powers serving as Harley Quinn's best friend and eventual romantic partner"),
    ("King Shark", "Male", "Max", "Anthropomorphic hammerhead shark with massive physique and simple-minded personality providing comic relief and unexpected tech-savvy skills"),
    ("Clay Puppington", "Male", "Max", "Alcoholic emotionally abusive father horse in Moral Orel stop-motion series representing dark satire of religious hypocrisy"),
    ("Orel Puppington", "Male", "Max", "Devout naive Christian boy in stop-motion Moral Orel who takes biblical lessons to tragic literal extremes learning painful truths"),
    ("Samurai Jack", "Male", "Adult Swim", "Stoic highly disciplined ancient Japanese samurai flung into dystopian future wearing white gi and wielding mystical indestructible katana"),
    ("Aku", "Male", "Adult Swim", "Shape-shifting evil demon of darkness with flaming eyebrows voiced by Mako tormenting Samurai Jack across time with shape-shifting wickedness"),
    ("The Scotsman", "Male", "Adult Swim", "Overweight kilt-wearing Scottish warrior with machine-gun leg and bagpipes befriending Samurai Jack through insult-based camaraderie"),

    # ====================
    # The CW / Paramount+ / BET / MTV / Miscellaneous
    # ====================
    ("Flash (CW Animated)", "Male", "The CW", "Red-suited speedster with lightning emblem running at superhuman velocities while quipping and protecting Central City in DC animated universe"),
    ("Green Arrow (CW)", "Male", "The CW", "Green-hooded archery vigilante with bow and trick arrows fighting corruption while brooding on island survival backstory"),
    ("Supergirl (CW)", "Female", "The CW", "Blonde Kryptonian cousin of Superman in red skirt and cape flying and fighting while balancing reporter career and alien heritage"),
    ("Star Trek: Prodigy - Dal", "Male", "Paramount+", "Purple-skinned adventurous alien teenager leading ragtag crew of young misfits aboard abandoned Starfleet vessel with mysterious past"),
    ("Gwyndala", "Female", "Paramount+", "Violet-haired daughter of Diviner with linguistic skills and moral compass navigating rebellion against father's tyranny aboard Protostar"),
    ("Kamp Koral - Young SpongeBob", "Male", "Paramount+", "Ten-year-old version of porous yellow sponge attending summer camp meeting young versions of future Bikini Bottom residents"),
    ("Rugrats (Reboot) - Tommy", "Male", "Paramount+", "CGI-rendered brave bald toddler leader in blue diaper maintaining original adventurous spirit for new generation of viewers"),
    ("Beavis", "Male", "MTV", "Blonde underbite teen in Metallica shirt obsessed with fire and scoring while laughing hehehe alongside partner Butt-head"),
    ("Butt-head", "Male", "MTV", "Brown-haired braces-wearing teen in AC/DC shirt providing deadpan commentary on music videos while sharing single brain cell with Beavis"),
    ("Daria Morgendorffer", "Female", "MTV", "Glasses-wearing sarcastic intelligent teenage girl in green jacket and combat boots observing suburban stupidity with monotone deadpan"),
    ("Jane Lane", "Female", "MTV", "Artist best friend of Daria with short black hair and red jacket sharing outsider perspective while pursuing creative ambitions"),
    ("Aeon Flux", "Female", "MTV", "Leather-clad sexy assassin with black hair and exaggerated thin frame in surreal futuristic dystopia dying repeatedly in experimental animation"),
    ("The Maxx", "Male", "MTV", "Large purple homeless superhero in mask with shifting reality between real world and Australian outback fantasy realm protecting social worker Julie"),
    ("Duckman", "Male", "MTV", "Obscene private detective duck with glasses and cigar solving cases in surreal Los Angeles while being terrible father and lecherous antihero"),
    ("South Park - Butters Stotch", "Male", "MTV", "Blonde innocent naive boy in turquoise jacket with signature Oh hamburgers catchphrase often grounded by abusive parents"),
    ("Good Times (Animated)", "Male", "BET", "Classic African-American family sitcom in animated adaptation featuring family patriarch navigating 1970s Chicago projects with humor"),
    ("Boondocks - Huey Freeman", "Male", "BET", "Ten-year-old African-American radical revolutionary with afro and perpetual scowl analyzing society through leftist intellectual lens"),
    ("Riley Freeman", "Male", "BET", "Eight-year-old brother of Huey with cornrows and wannabe gangsta persona obsessed with rap culture and thug life aesthetics"),
    ("Granddad Freeman", "Male", "BET", "Elderly guardian of Huey and Riley with grey mustache trying to enjoy retirement while dealing with two difficult grandsons"),
    ("Uncle Ruckus", "Male", "BET", "Self-hating black man with glass eye who worships white people while claiming to have re-vitiligo causing his skin color"),

    # ====================
    # YouTube Kids / YouTube Originals
    # ====================
    ("Blippi", "Male", "YouTube Kids", "Orange-blue costumed energetic educational entertainer in glasses and bow tie exploring museums construction sites and teaching colors"),
    ("Cocomelon - JJ", "Male", "YouTube Kids", "Small toddler with tuft of blonde hair in pajamas singing nursery rhymes alongside animated family and animal friends"),
    ("Ryan (Ryan's World)", "Male", "YouTube Kids", "Child YouTube star reviewing toys and performing science experiments with family in bright colored t-shirts and enthusiastic delivery"),
    ("Pinkfong", "Male", "YouTube Kids", "Pink fox character originating Baby Shark phenomenon with educational songs and dances featuring colorful sea creatures"),
    ("Hogi", "Male", "YouTube Kids", "Green dinosaur companion to Pinkfong exploring educational concepts through musical adventures in animated preschool content"),
    ("Masha (Masha and the Bear)", "Female", "YouTube Kids", "Mischievous blonde Russian girl in pink dress and headscarf causing chaos for retired circus bear in forest setting"),
    ("The Bear (Masha)", "Male", "YouTube Kids", "Patient retired circus bear who constantly rescues and disciplines hyperactive Masha while maintaining forest home and garden"),
    ("Talking Tom", "Male", "YouTube Kids", "Grey anthropomorphic cat who repeats phrases and gets into urban adventures with group of talking animal friends in mobile game adaptation"),
    ("Talking Angela", "Female", "YouTube Kids", "White cat singer and girlfriend of Talking Tom with pink aesthetic pursuing music career alongside animal friend group"),
    ("Morphle", "Male", "YouTube Kids", "Small red magical creature who shape-shifts into anything child owner imagines teaching problem-solving through transformation adventures"),
    ("Arpo", "Male", "YouTube Kids", "Tall robotic babysitter with no dialogue providing slapstick child care through physical comedy in Korean animated YouTube series"),

    # ====================
    # Nickelodeon (Additional / Nick at Nite / TeenNick / The N / Nick GAS)
    # ====================
    ("Doug Funnie", "Male", "Nickelodeon", "Nerdy eleven-year-old boy with green sweater vest and white shirt who narrates life through journal entries while imagining superhero alter-ego Quailman"),
    ("Skeeter Valentine", "Male", "Nickelodeon", "Blue-skinned best friend of Doug with exaggerated honking laugh and yellow shirt providing loyal enthusiastic support"),
    ("Patti Mayonnaise", "Female", "Nickelodeon", "Blonde athletic girl in purple and green who is Doug's unrequited crush with kind personality and eventual reciprocated feelings"),
    ("Roger Klotz", "Male", "Nickelodeon", "Green-skinned bully with leather jacket and greasy hair who eventually becomes more complex character beyond simple antagonist"),
    ("Ginger Foutley", "Female", "Nickelodeon", "Red-haired freckled preteen girl navigating middle school social hierarchy while writing poetry in journal-based animated series"),
    ("CatDog", "Male", "Nickelodeon", "Conjoined twin brothers one refined cat one crude dog sharing single body with no visible tail end causing constant conflict"),
    ("Henry (KaBlam!)", "Male", "Nickelodeon", "Comic-book boy host of sketch comedy anthology show alongside June interacting with animated shorts through paper-cut aesthetic"),
    ("June (KaBlam!)", "Female", "Nickelodeon", "Paper-cut girl co-host of KaBlam with blonde hair serving as energetic foil to Henry in comic-book-styled wrap-around segments"),
    ("Otto Rocket", "Male", "Nickelodeon", "Extreme sports-obsessed teenage boy with wild red hair and sunglasses leading quartet in Ocean Shores with catchphrase Woogity"),
    ("Reggie Rocket", "Female", "Nickelodeon", "Purple-haired athletic sister of Otto who publishes extreme sports magazine while serving as voice of reason in Rocket Power group"),
    ("Twister Rodriguez", "Male", "Nickelodeon", "Hispanic videographer friend with orange hair who documents extreme sports adventures while providing camera-based commentary"),
    ("Sam Dullard", "Male", "Nickelodeon", "Tech-savvy newcomer from Kansas with glasses who joins Rocket Power group bringing computer skills to extreme sports crew"),
    ("Ned Bigby", "Male", "Nickelodeon", "Brown-haired middle school student in orange shirt who breaks fourth wall providing survival guide tips for navigating adolescent challenges"),
    ("Moze", "Female", "Nickelodeon", "Blonde athletic best friend of Ned with tomboy style and volleyball skills navigating middle school gender expectations"),
    ("Cookie", "Male", "Nickelodeon", "Tech-obsessed friend with glasses and catchphrase totally absolutely who hacks school systems while crushing on various classmates"),
    ("Carly Shay", "Female", "Nickelodeon", "Brown-haired teenage web show host who creates iCarly with friends from apartment featuring random dancing and spaghetti tacos"),
    ("Sam Puckett", "Female", "Nickelodeon", "Blonde aggressive co-host with butter sock and fried chicken obsession who provides chaotic violent energy to iCarly webcast"),
    ("Freddie Benson", "Male", "Nickelodeon", "Tech-producer of iCarly with crush on Carly wearing graphic tees while operating camera despite constant Sam abuse"),
    ("Spencer Shay", "Male", "Nickelodeon", "Eccentric older brother and guardian of Carly who creates elaborate fire-prone sculptures while providing unconventional adult supervision"),
    ("Gibby Gibson", "Male", "Nickelodeon", "Shirtless chubby classmate who shouts his own name and frequently removes shirt for comedic effect while performing random breakdancing"),
    ("Drake Parker", "Male", "Nickelodeon", "Brown-haired guitarist and heartthrob with lazy personality and signature blue hoodie causing trouble while pursuing music career"),
    ("Josh Nichols", "Male", "Nickelodeon", "Responsible stepbrother with blonde hair and academic focus who constantly bails Drake out of schemes while running school AV club"),
    ("Megan Parker", "Female", "Nickelodeon", "Precocious mischievous younger sister with blonde pigtails who masterminds pranks against brothers with diabolical intelligence"),
    ("Kenan Rockmore", "Male", "Nickelodeon", "African-American teen in orange shirt working at grocery store alongside Kel in sitcom based on comedy duo's real partnership"),
    ("Kel Kimble", "Male", "Nickelodeon", "Excitable teen with orange soda obsession and catchphrase Aw here it goes providing chaotic energy to Kenan and Kel schemes"),
    ("Amanda Bynes (The Amanda Show)", "Female", "Nickelodeon", "Blonde teenage host performing various sketch characters including Judge Trudy and Penelope Taynt in variety comedy format"),
    ("Alex Mack", "Female", "Nickelodeon", "Brown-haired teenage girl in flannel and backwards cap who gains telekinetic and morphing powers from chemical accident"),
    ("Clarissa Darling", "Female", "Nickelodeon", "Blonde 90s teenage girl in eclectic fashion who breaks fourth wall explaining adolescent life through video game metaphors"),
    ("Mr. Wizard", "Male", "Nickelodeon", "Real science educator in sweater performing hands-on experiments with children guests teaching scientific method on classic Nick"),
    ("Stick Stickly", "Male", "Nickelodeon", "Popsicle-stick puppet host with googly eyes addressing mail and hosting Nick in the Afternoon block with catchy address song"),
    ("Face (Nick Jr.)", "Male", "Nick Jr.", "Animated multicolored face mascot of Nick Jr. who transitions between bumpers with trumpet sounds and cheerful greetings"),

    # ====================
    # Tiny TV / Playhouse Disney / Noggin / The N
    # ====================
    ("Bear (Big Blue House)", "Male", "Playhouse Disney", "Large friendly orange bear in overalls who welcomes viewers into his house while smelling everything and singing goodbye songs"),
    ("Tutter", "Male", "Playhouse Disney", "Small blue mouse living in hole in Bear's house with anxiety issues and obsession with cheese"),
    ("Pip (Bear in the Big Blue House)", "Female", "Playhouse Disney", "Purple otter with high energy and love of dancing alongside pop providing young-child perspective in Big Blue House"),
    ("Rolie Polie Olie", "Male", "Playhouse Disney", "Round robot boy in 1950s-inspired retro-futuristic world with circular family navigating childhood through shapes and imaginative play"),
    ("JoJo (JoJo's Circus)", "Female", "Playhouse Disney", "Orange-haired clown girl with red nose and blue dress attending circus school learning physical skills and social lessons"),
    ("Stanley", "Male", "Playhouse Disney", "Animal-obsessed boy with blonde hair who uses Great Big Book of Everything to learn about creatures through song and imagination"),
    ("Oswald", "Male", "Noggin", "Blue friendly octopus with bowler hat and pet hot dog Weenie navigating Big City with gentle polite demeanor and ukulele playing"),
    ("Weenie", "Female", "Noggin", "Hot dog-shaped pet dog of Oswald who behaves exactly like canine despite food appearance providing loyal companionship"),
    ("Maggie (Maggie and the Ferocious Beast)", "Female", "Noggin", "Red-haired imaginative girl in yellow dress who visits Nowhere Land to have adventures with polka-dotted Beast and pig Hamilton"),
    ("Beast", "Male", "Noggin", "Large yellow polka-dotted gentle monster who is ironically not ferocious despite name ferrying Maggie around Nowhere Land"),
    ("Franklin the Turtle", "Male", "Noggin", "Green turtle with red cap and scarf who learns life lessons about friendship and honesty alongside woodland animal friends"),
    ("Little Bear", "Male", "Noggin", "Small brown bear in tunic who explores forest with animal friends while having gentle adventures and returning home to Mother Bear"),
    ("Maisie Mouse", "Female", "Noggin", "Small white mouse with bows and colorful wardrobe exploring everyday toddler experiences through gentle discovery-based stories"),
    ("Kipper", "Male", "Noggin", "Orange British dog with gentle personality and simple adventures alongside pig and other animal friends through watercolor-style animation"),
    ("Miffy", "Female", "Noggin", "Small white rabbit with minimalist design and primary-color clothing learning basic concepts through simple Dutch-origin stories"),
    ("Blues Clues - Mailbox", "Male", "Noggin", "Purple talking mailbox who delivers letters to Blue and Steve with enthusiastic Mail Time song interruption"),
    ("Sid the Science Kid", "Male", "PBS Kids", "Curious African-American preschooler with green cap who explores scientific questions through observation and Super Fab Lab experiments"),
    ("WordGirl", "Female", "PBS Kids", "Superheroine with red costume and vocabulary theme who defeats villains while teaching word definitions through context"),
    ("Super Grover", "Male", "PBS Kids", "Blue furry superhero monster alter ego of Grover who crashes while attempting rescues parodying Superman in Sesame Street segments"),
    ("Wild Kratts - Aviva Corcovado", "Female", "PBS Kids", "Hispanic inventor of Creature Power Suits with purple streak in hair providing technological solutions for animal rescue missions"),

    # ====================
    # Pluto TV / Tubi / Crackle / Freevee / Xumo (FAST Channels)
    # ====================
    ("Inspector Gadget", "Male", "Pluto TV (FAST channels)", "Cyborg detective in grey trench coat with extending limbs and hat-copter whose niece Penny and dog Brain actually solve cases"),
    ("Penny (Inspector Gadget)", "Female", "Pluto TV (FAST channels)", "Blonde pigtailed niece who secretly solves all of Inspector Gadget's cases using computer book and detective skills"),
    ("Brain (Inspector Gadget)", "Male", "Pluto TV (FAST channels)", "Beige dog with collar who walks on hind legs communicating through pantomime while protecting Gadget from Dr. Claw schemes"),
    ("He-Man", "Male", "Pluto TV (FAST channels)", "Blonde muscular prince Adam who transforms into most powerful man in universe using Power Sword to protect Castle Grayskull"),
    ("Skeletor", "Male", "Pluto TV (FAST channels)", "Blue skull-faced evil sorcerer with yellow hood and staff who cackles maniacally while failing to conquer Grayskull"),
    ("She-Ra (Classic)", "Female", "Pluto TV (FAST channels)", "Blonde twin sister of He-Man with golden tiara and white costume leading Great Rebellion against Hordak on Etheria"),
    ("ThunderCats - Lion-O", "Male", "Pluto TV (FAST channels)", "Orange-furred Lord of ThunderCats with Sword of Omens and claw shield leading survivors from Thundera against Mumm-Ra"),
    ("Cheetara", "Female", "Pluto TV (FAST channels)", "Fast orange-spotted female ThunderCat with staff whose sixth sense and super-speed provide tactical advantage"),
    ("Panthro", "Male", "Pluto TV (FAST channels)", "Bald muscular blue ThunderCat mechanic with nunchucks and strength building all team vehicles and technology"),
    ("Tygra", "Male", "Pluto TV (FAST channels)", "Orange tiger-striped ThunderCat architect with bolo whip and invisibility power serving as Lion-O's adviser"),
    ("Mumm-Ra", "Male", "Pluto TV (FAST channels)", "Ancient bandaged demon mummy who transforms into muscular form by invoking Ancient Spirits of Evil against ThunderCats"),
    ("Voltron - Keith", "Male", "Pluto TV (FAST channels)", "Black-haired leader of Voltron Force piloting Black Lion forming head of giant combining robot defender of universe"),
    ("Lance (Voltron)", "Male", "Pluto TV (FAST channels)", "Red Lion pilot and sharpshooter with blue outfit and cocky personality forming right arm of Voltron combination"),
    ("Transformers - Optimus Prime", "Male", "Pluto TV (FAST channels)", "Red and blue truck transforming Autobot leader with faceplate and iconic voice who fights Decepticons to protect freedom"),
    ("Bumblebee (Transformers)", "Male", "Pluto TV (FAST channels)", "Small yellow Autobot scout who transforms into compact car communicating through radio clips and beeps"),
    ("Megatron", "Male", "Pluto TV (FAST channels)", "Grey Decepticon leader who transforms into Walther pistol with fusion cannon arm determined to conquer Cybertron"),
    ("Starscream", "Male", "Pluto TV (FAST channels)", "Red and grey jet Decepticon who constantly schemes to overthrow Megatron with cowardly high-pitched voice"),
    ("G.I. Joe - Duke", "Male", "Pluto TV (FAST channels)", "Blonde first sergeant field leader of Joes in khaki shirt leading missions against Cobra with strategic command ability"),
    ("Cobra Commander", "Male", "Pluto TV (FAST channels)", "Blue-hooded or silver-masked squeaky-voiced dictator leading Cobra organization with incompetent schemes against G.I. Joe"),
    ("Snake Eyes", "Male", "Pluto TV (FAST channels)", "Silent black-masked ninja commando who never speaks and has pet wolf Timber while maintaining mysterious past"),
    ("Garfield", "Male", "Pluto TV (FAST channels)", "Orange overweight lasagna-loving sarcastic cat who hates Mondays abuses canine companion Odie and torments owner Jon Arbuckle"),
    ("Odie", "Male", "Pluto TV (FAST channels)", "Yellow beagle with long tongue and simple mind who is Garfield's frequent victim yet remains perpetually happy"),
    ("Alvin (Chipmunks)", "Male", "Pluto TV (FAST channels)", "Red-sweatered chipmunk and lead singer of trio causing mischief with signature high-pitched voice and leader personality"),
    ("Simon (Chipmunks)", "Male", "Pluto TV (FAST channels)", "Blue-sweatered intellectual chipmunk brother with glasses providing voice of reason and scientific knowledge"),
    ("Theodore (Chipmunks)", "Male", "Pluto TV (FAST channels)", "Green-sweatered chubby chipmunk with sweet naive personality and food obsession serving as baby of the group"),
    ("Smurfs - Papa Smurf", "Male", "Pluto TV (FAST channels)", "Red-hatted elderly bearded leader of blue Smurf village with magical alchemy knowledge dispensing wisdom to community"),
    ("Smurfette", "Female", "Pluto TV (FAST channels)", "Blonde originally-created-by-Gargamel Smurf with white dress and heels who became true Smurf through Papa's magic"),
    ("Brainy Smurf", "Male", "Pluto TV (FAST channels)", "Glasses-wearing know-it-all Smurf with annoying lecture habit frequently getting hit with mallet by other Smurfs"),
    ("Clumsy Smurf", "Male", "Pluto TV (FAST channels)", "Accident-prone Smurf with blue hat askew who constantly trips and drops things yet remains lovable village member"),
    ("Gargamel", "Male", "Pluto TV (FAST channels)", "Bald black-robed evil wizard with tooth obsession and cat Azrael who constantly attempts to capture and eat Smurfs"),
    ("Azrael", "Male", "Pluto TV (FAST channels)", "Orange cat companion to Gargamel who is smarter than his master and often wants to eat Smurfs himself"),
    ("Casper the Friendly Ghost", "Male", "Pluto TV (FAST channels)", "Small transparent ghost who wants to befriend everyone despite scaring people accidentally due to ghostly nature"),
    ("Richie Rich", "Male", "Pluto TV (FAST channels)", "Wealthiest boy in world with blonde hair and dollar-sign motif solving problems using money and inventions while remaining generous"),
    ("Felix the Cat", "Male", "Pluto TV (FAST channels)", "Black cartoon cat with white face and magic bag of tricks from silent film era navigating surreal adventures"),
    ("Woody Woodpecker", "Male", "Pluto TV (FAST channels)", "Blue and red woodpecker with maniacal laugh and red crest causing chaos wherever he goes with signature ha-ha-ha-HA-ha"),
]

# ============================================================
# WRITE CSV
# ============================================================
with open(OUTPUT_FILE, "w", newline="", encoding="utf-8") as f:
    writer = csv.writer(f)
    writer.writerow(["Character Name", "Gender", "Network/Brand Reference", "Descriptor"])
    writer.writerows(characters)

print(f"CSV written to {OUTPUT_FILE} with {len(characters)} character entries.")